export enum RosaCliCommand {
  UserRole = 'rosa create user-role',
  LinkUserRole = 'rosa link user-role <arn>',
  OcmRole = 'rosa create ocm-role',
  AdminOcmRole = 'rosa create ocm-role --admin',
  ListOcmRole = 'rosa list ocm-role',
  LinkOcmRole = 'rosa link ocm-role <arn>',
  ListUserRole = 'rosa list user-role',
  VerifyQuota = 'rosa verify quota',
  WhoAmI = 'rosa whoami',
  CreateAccountRolesAuto = 'rosa create account-roles --mode auto',
  CreateAccountRoles = 'rosa create account-roles',
  CreateAccountRolesHCP = 'rosa create account-roles --hosted-cp',
  CreateAccountRolesHCPAuto = 'rosa create account-roles --hosted-cp --mode auto',
  CreateCluster = 'rosa create cluster',
}
