import Login from '../../pageobjects/login.page';
import ClusterListPage from '../../pageobjects/ClusterList.page';
import CreateRosaWizardPage from '../../pageobjects/CreateRosaWizard.page';

const clusterFieldValidations = require('../../fixtures/rosa/RosaClusterClassicWizardValidation.json');

// awsAccountID,rolePrefix and installerARN are set by prerun script for smoke requirements.
const awsAccountID = Cypress.env('QE_AWS_ID');
const rolePrefix = 'cypress-account-roles';
const installerARN = 'arn:aws:iam::' + awsAccountID + ':role/' + rolePrefix + '-Installer-Role';
const clusterName = `smkrosa-` + (Math.random() + 1).toString(36).substring(7);

describe('Rosa Classic cluster wizard validations', { tags: ['smoke'] }, () => {
  before(() => {
    cy.visit('/');
    Login.isLoginPageUrl();
    Login.login();

    ClusterListPage.isClusterListUrl();
    ClusterListPage.waitForDataReady();
    cy.getByTestId('create_cluster_btn').should('be.visible');
  });

  it('Open Rosa cluster wizard', () => {
    cy.getByTestId('create_cluster_btn').click();
    CreateRosaWizardPage.rosaCreateClusterButton().click();
    CreateRosaWizardPage.rosaClusterWithWeb().should('be.visible').click();
    CreateRosaWizardPage.isCreateRosaPage();
    cy.get('.spinner-loading-text').should('not.exist');
  });

  it('Step - Control plane - widget validations', () => {
    CreateRosaWizardPage.isControlPlaneTypeScreen();
    CreateRosaWizardPage.rosaNextButton().should('not.be.disabled');
    CreateRosaWizardPage.rosaBackButton().should('be.disabled');
    CreateRosaWizardPage.rosaCancelButton().should('not.be.disabled');
    CreateRosaWizardPage.selectStandaloneControlPlaneTypeOption();
    CreateRosaWizardPage.rosaNextButton().click({ force: true });
  });

  it('Step - Accounts and roles - widget validations', () => {
    CreateRosaWizardPage.isAccountsAndRolesScreen();
    CreateRosaWizardPage.selectAWSInfrastructureAccount(awsAccountID);
    CreateRosaWizardPage.refreshInfrastructureAWSAccountButton().click();
    CreateRosaWizardPage.waitForARNList();
    CreateRosaWizardPage.selectInstallerRole(installerARN);
    CreateRosaWizardPage.rosaNextButton().click({ force: true });
  });

  it('Step - Cluster Settings - widget validations', () => {
    cy.get(CreateRosaWizardPage.clusterNameInput).type(clusterName);
    CreateRosaWizardPage.advancedEncryptionLink().click();
    CreateRosaWizardPage.useCustomKMSKeyRadio().check();
    CreateRosaWizardPage.rosaNextButton().click({ force: true });
    CreateRosaWizardPage.kmsKeyARNHelpText().should('be.visible').contains('Field is required.');
    CreateRosaWizardPage.inputCustomerManageKeyARN(
      clusterFieldValidations.ClusterSettings.Details.KeyARNs[0].WrongFormatValue,
    );
    CreateRosaWizardPage.kmsKeyARNHelpText()
      .should('be.visible')
      .contains(clusterFieldValidations.ClusterSettings.Details.KeyARNs[0].WrongFormatError);
    CreateRosaWizardPage.inputCustomerManageKeyARN(
      clusterFieldValidations.ClusterSettings.Details.KeyARNs[1].WrongFormatWithWhitespace,
    );
    CreateRosaWizardPage.kmsKeyARNHelpText()
      .should('be.visible')
      .contains(
        clusterFieldValidations.ClusterSettings.Details.KeyARNs[1].WrongFormatWithWhitespaceError,
      );
    CreateRosaWizardPage.useDefaultKMSKeyRadio().check();
    CreateRosaWizardPage.rosaNextButton().should('not.be.disabled');
    CreateRosaWizardPage.rosaBackButton().should('not.be.disabled');
    CreateRosaWizardPage.rosaCancelButton().should('not.be.disabled');
    CreateRosaWizardPage.rosaNextButton().click({ force: true });
  });

  it('Step - Cluster Settings - machine pool- Node count section - widget validations', () => {
    CreateRosaWizardPage.isClusterMachinepoolsScreen();
    CreateRosaWizardPage.enableAutoScaling();
    CreateRosaWizardPage.setMinimumNodeCount('0');
    cy.get('span')
      .contains(
        clusterFieldValidations.ClusterSettings.Machinepool.NodeCount.SingleZone.LowerLimitError,
      )
      .should('be.visible');
    CreateRosaWizardPage.setMinimumNodeCount('200');
    cy.get('span')
      .contains(
        clusterFieldValidations.ClusterSettings.Machinepool.NodeCount.SingleZone.UpperLimitError,
      )
      .should('be.visible');
    cy.get('span')
      .contains(
        clusterFieldValidations.ClusterSettings.Machinepool.NodeCount.SingleZone
          .MinAndMaxLimitDependencyError,
      )
      .should('be.visible');
    CreateRosaWizardPage.setMinimumNodeCount('2');
    CreateRosaWizardPage.setMaximumNodeCount('200');
    cy.get('span')
      .contains(
        clusterFieldValidations.ClusterSettings.Machinepool.NodeCount.SingleZone.UpperLimitError,
      )
      .should('be.visible');
    CreateRosaWizardPage.setMaximumNodeCount('0');
    cy.get('span')
      .contains(
        clusterFieldValidations.ClusterSettings.Machinepool.NodeCount.SingleZone.LowerLimitError,
      )
      .should('be.visible');
    CreateRosaWizardPage.setMaximumNodeCount('2');
    CreateRosaWizardPage.minimumNodeCountPlusButton().click();
    cy.get('span')
      .contains(
        clusterFieldValidations.ClusterSettings.Machinepool.NodeCount.SingleZone
          .MinAndMaxLimitDependencyError,
      )
      .should('be.visible');
    CreateRosaWizardPage.maximumNodeCountPlusButton().click();
    cy.get('span')
      .contains(
        clusterFieldValidations.ClusterSettings.Machinepool.NodeCount.SingleZone
          .MinAndMaxLimitDependencyError,
      )
      .should('not.exist');
    CreateRosaWizardPage.maximumNodeCountMinusButton().click();
    cy.get('span')
      .contains(
        clusterFieldValidations.ClusterSettings.Machinepool.NodeCount.SingleZone
          .MinAndMaxLimitDependencyError,
      )
      .should('be.visible');
    CreateRosaWizardPage.minimumNodeCountMinusButton().click();
    cy.get('span')
      .contains(
        clusterFieldValidations.ClusterSettings.Machinepool.NodeCount.SingleZone
          .MinAndMaxLimitDependencyError,
      )
      .should('not.exist');
    CreateRosaWizardPage.rosaBackButton().click();
    CreateRosaWizardPage.selectAvailabilityZone('Multi-zone');
    CreateRosaWizardPage.rosaNextButton().click({ force: true });
    CreateRosaWizardPage.setMinimumNodeCount('0');
    cy.get('span')
      .contains(
        clusterFieldValidations.ClusterSettings.Machinepool.NodeCount.MultiZone.LowerLimitError,
      )
      .should('be.visible');
    CreateRosaWizardPage.setMinimumNodeCount('200');
    cy.get('span')
      .contains(
        clusterFieldValidations.ClusterSettings.Machinepool.NodeCount.MultiZone.UpperLimitError,
      )
      .should('be.visible');
    CreateRosaWizardPage.setMaximumNodeCount('2');
    cy.get('span')
      .contains(
        clusterFieldValidations.ClusterSettings.Machinepool.NodeCount.MultiZone
          .MinAndMaxLimitDependencyError,
      )
      .should('be.visible');
    CreateRosaWizardPage.setMinimumNodeCount('2');
    CreateRosaWizardPage.setMaximumNodeCount('200');
    cy.get('span')
      .contains(
        clusterFieldValidations.ClusterSettings.Machinepool.NodeCount.MultiZone.UpperLimitError,
      )
      .should('be.visible');
    CreateRosaWizardPage.setMaximumNodeCount('0');
    cy.get('span')
      .contains(
        clusterFieldValidations.ClusterSettings.Machinepool.NodeCount.MultiZone.LowerLimitError,
      )
      .should('be.visible');
    CreateRosaWizardPage.setMaximumNodeCount('2');
    CreateRosaWizardPage.minimumNodeCountPlusButton().click();
    cy.get('span')
      .contains(
        clusterFieldValidations.ClusterSettings.Machinepool.NodeCount.MultiZone
          .MinAndMaxLimitDependencyError,
      )
      .should('be.visible');
    CreateRosaWizardPage.maximumNodeCountPlusButton().click();
    cy.get('span')
      .contains(
        clusterFieldValidations.ClusterSettings.Machinepool.NodeCount.MultiZone
          .MinAndMaxLimitDependencyError,
      )
      .should('not.exist');
    CreateRosaWizardPage.maximumNodeCountMinusButton().click();
    cy.get('span')
      .contains(
        clusterFieldValidations.ClusterSettings.Machinepool.NodeCount.MultiZone
          .MinAndMaxLimitDependencyError,
      )
      .should('be.visible');
    CreateRosaWizardPage.minimumNodeCountMinusButton().click();
    cy.get('span')
      .contains(
        clusterFieldValidations.ClusterSettings.Machinepool.NodeCount.MultiZone
          .MinAndMaxLimitDependencyError,
      )
      .should('not.exist');
  });
  it('Step - Cluster Settings - machine pool- Cluster autoscaling section - widget validations', () => {
    CreateRosaWizardPage.editClusterAutoscalingSettingsButton().click();
    CreateRosaWizardPage.clusterAutoscalingLogVerbosityInput().type('{selectAll}').type('0');
    cy.get('div')
      .contains(
        clusterFieldValidations.ClusterSettings.Machinepool.ClusterAutoscaling
          .LogVerbosityLimitError,
      )
      .should('be.visible');
    CreateRosaWizardPage.clusterAutoscalingLogVerbosityInput().type('{selectAll}').type('7');
    cy.get('div')
      .contains(
        clusterFieldValidations.ClusterSettings.Machinepool.ClusterAutoscaling
          .LogVerbosityLimitError,
      )
      .should('be.visible');
    CreateRosaWizardPage.clusterAutoscalingLogVerbosityInput().type('{selectAll}').type('3');
    cy.get('div')
      .contains(
        clusterFieldValidations.ClusterSettings.Machinepool.ClusterAutoscaling
          .LogVerbosityLimitError,
      )
      .should('not.exist');
    CreateRosaWizardPage.clusterAutoscalingMaxNodeProvisionTimeInput().clear();
    cy.get('div')
      .contains(
        clusterFieldValidations.ClusterSettings.Machinepool.ClusterAutoscaling.RequiredFieldError,
      )
      .should('be.visible');
    CreateRosaWizardPage.clusterAutoscalingMaxNodeProvisionTimeInput().clear().type('8H');
    cy.get('div')
      .contains(
        clusterFieldValidations.ClusterSettings.Machinepool.ClusterAutoscaling
          .InvalidTimeValueError,
      )
      .should('be.visible');
    CreateRosaWizardPage.clusterAutoscalingMaxNodeProvisionTimeInput().clear().type('90k');
    cy.get('div')
      .contains(
        clusterFieldValidations.ClusterSettings.Machinepool.ClusterAutoscaling
          .InvalidTimeValueError,
      )
      .should('be.visible');
    CreateRosaWizardPage.clusterAutoscalingMaxNodeProvisionTimeInput().clear().type('8s');
    cy.get('div')
      .contains(
        clusterFieldValidations.ClusterSettings.Machinepool.ClusterAutoscaling
          .InvalidTimeValueError,
      )
      .should('not.exist');
    CreateRosaWizardPage.clusterAutoscalingBalancingIgnoredLabelsInput()
      .clear()
      .type('test with whitespace,test');
    cy.get('div')
      .contains(
        clusterFieldValidations.ClusterSettings.Machinepool.ClusterAutoscaling
          .WhitespaceLabelValueError,
      )
      .should('be.visible');
    CreateRosaWizardPage.clusterAutoscalingBalancingIgnoredLabelsInput().clear().type('test,test,');
    cy.get('div')
      .contains(
        clusterFieldValidations.ClusterSettings.Machinepool.ClusterAutoscaling.EmptyLabelValueError,
      )
      .should('be.visible');
    CreateRosaWizardPage.clusterAutoscalingBalancingIgnoredLabelsInput()
      .clear()
      .type('test@434$,123,&test_(t)35435');
    cy.get('div').contains('Empty labels are not allowed').should('not.exist');
    CreateRosaWizardPage.clusterAutoscalingCoresTotalMinInput().type('{selectAll}').type('10');
    CreateRosaWizardPage.clusterAutoscalingCoresTotalMaxInput().type('{selectAll}').type('9');
    cy.get('div')
      .contains(
        clusterFieldValidations.ClusterSettings.Machinepool.ClusterAutoscaling.MinMaxLimitError,
      )
      .should('be.visible');
    CreateRosaWizardPage.clusterAutoscalingCoresTotalMinInput().type('{selectAll}').type('9');
    CreateRosaWizardPage.clusterAutoscalingCoresTotalMaxInput().type('{selectAll}').type('10');
    cy.get('div')
      .contains(
        clusterFieldValidations.ClusterSettings.Machinepool.ClusterAutoscaling.MinMaxLimitError,
      )
      .should('not.exist');
    CreateRosaWizardPage.clusterAutoscalingMemoryTotalMinInput().type('{selectAll}').type('10');
    CreateRosaWizardPage.clusterAutoscalingMemoryTotalMaxInput().type('{selectAll}').type('9');
    cy.get('div')
      .contains(
        clusterFieldValidations.ClusterSettings.Machinepool.ClusterAutoscaling.MinMaxLimitError,
      )
      .should('be.visible');
    CreateRosaWizardPage.clusterAutoscalingMemoryTotalMinInput().type('{selectAll}').type('9');
    CreateRosaWizardPage.clusterAutoscalingMemoryTotalMaxInput().type('{selectAll}').type('10');
    cy.get('div')
      .contains(
        clusterFieldValidations.ClusterSettings.Machinepool.ClusterAutoscaling.MinMaxLimitError,
      )
      .should('not.exist');
    CreateRosaWizardPage.clusterAutoscalingGPUsInput().type('{selectAll}').type('test');
    cy.get('div')
      .contains(
        clusterFieldValidations.ClusterSettings.Machinepool.ClusterAutoscaling.InvalidGPUValueError,
      )
      .should('be.visible');
    CreateRosaWizardPage.clusterAutoscalingGPUsInput().type('{selectAll}').type('test:10:5');
    cy.get('div')
      .contains(
        clusterFieldValidations.ClusterSettings.Machinepool.ClusterAutoscaling.InvalidGPUValueError,
      )
      .should('be.visible');
    CreateRosaWizardPage.clusterAutoscalingGPUsInput().type('{selectAll}').type('test:10:5,');
    cy.get('div')
      .contains(
        clusterFieldValidations.ClusterSettings.Machinepool.ClusterAutoscaling.InvalidGPUValueError,
      )
      .should('be.visible');
    CreateRosaWizardPage.clusterAutoscalingGPUsInput()
      .type('{selectAll}')
      .type('test:10:12,test:1:5');
    cy.get('div')
      .contains(
        clusterFieldValidations.ClusterSettings.Machinepool.ClusterAutoscaling.InvalidGPUValueError,
      )
      .should('not.exist');
    CreateRosaWizardPage.clusterAutoscalingScaleDownUtilizationThresholdInput()
      .type('{selectAll}')
      .type('1.5');
    cy.get('div')
      .contains(
        clusterFieldValidations.ClusterSettings.Machinepool.ClusterAutoscaling.ThreasholdLimitError,
      )
      .should('be.visible');
    CreateRosaWizardPage.clusterAutoscalingScaleDownUtilizationThresholdInput()
      .type('{selectAll}')
      .type('0.5');

    CreateRosaWizardPage.clusterAutoscalingScaleDownUnneededTimeInput()
      .type('{selectAll}')
      .type('7H');
    cy.get('div')
      .contains(
        clusterFieldValidations.ClusterSettings.Machinepool.ClusterAutoscaling
          .InvalidTimeValueError,
      )
      .should('be.visible');
    CreateRosaWizardPage.clusterAutoscalingScaleDownUnneededTimeInput()
      .type('{selectAll}')
      .type('7h');
    cy.get('div')
      .contains(
        clusterFieldValidations.ClusterSettings.Machinepool.ClusterAutoscaling
          .InvalidTimeValueError,
      )
      .should('not.exist');

    CreateRosaWizardPage.clusterAutoscalingScaleDownDelayAfterAddInput()
      .type('{selectAll}')
      .type('8Sec');
    cy.get('div')
      .contains(
        clusterFieldValidations.ClusterSettings.Machinepool.ClusterAutoscaling
          .InvalidTimeValueError,
      )
      .should('be.visible');
    CreateRosaWizardPage.clusterAutoscalingScaleDownDelayAfterAddInput()
      .type('{selectAll}')
      .type('8s');
    cy.get('div')
      .contains(
        clusterFieldValidations.ClusterSettings.Machinepool.ClusterAutoscaling
          .InvalidTimeValueError,
      )
      .should('not.exist');

    CreateRosaWizardPage.clusterAutoscalingScaleDownDelayAfterDeleteInput()
      .type('{selectAll}')
      .type('10milli');
    cy.get('div')
      .contains(
        clusterFieldValidations.ClusterSettings.Machinepool.ClusterAutoscaling
          .InvalidTimeValueError,
      )
      .should('be.visible');

    CreateRosaWizardPage.clusterAutoscalingScaleDownDelayAfterDeleteInput()
      .type('{selectAll}')
      .type('10s');
    cy.get('div')
      .contains(
        clusterFieldValidations.ClusterSettings.Machinepool.ClusterAutoscaling
          .InvalidTimeValueError,
      )
      .should('not.exist');

    CreateRosaWizardPage.clusterAutoscalingScaleDownDelayAfterFailureInput()
      .type('{selectAll}')
      .type('5M');
    cy.get('div')
      .contains(
        clusterFieldValidations.ClusterSettings.Machinepool.ClusterAutoscaling
          .InvalidTimeValueError,
      )
      .should('be.visible');

    CreateRosaWizardPage.clusterAutoscalingScaleDownDelayAfterFailureInput()
      .type('{selectAll}')
      .type('5m');
    cy.get('div')
      .contains(
        clusterFieldValidations.ClusterSettings.Machinepool.ClusterAutoscaling
          .InvalidTimeValueError,
      )
      .should('not.exist');

    CreateRosaWizardPage.clusterAutoscalingRevertAllToDefaultsButton().click();
    CreateRosaWizardPage.clusterAutoscalingCloseButton().click();
  });
  it('Step - Cluster Settings - machine pool- Root disk size and node labels section - widget validations', () => {
    CreateRosaWizardPage.rootDiskSizeInput().type('{selectAll}').type('125');
    cy.get('div')
      .contains(clusterFieldValidations.ClusterSettings.Machinepool.RootDiskSize.LimitError)
      .should('be.visible');
    CreateRosaWizardPage.rootDiskSizeInput().type('{selectAll}').type('16385');
    cy.get('div')
      .contains(clusterFieldValidations.ClusterSettings.Machinepool.RootDiskSize.LimitError)
      .should('be.visible');
    CreateRosaWizardPage.rootDiskSizeInput().clear().type('{selectAll}').type('test');
    cy.get('div')
      .contains(clusterFieldValidations.ClusterSettings.Machinepool.RootDiskSize.NonSupportedValue)
      .should('be.visible');
    CreateRosaWizardPage.rootDiskSizeInput().clear().type('{selectAll}').type('555');
    CreateRosaWizardPage.editNodeLabelLink().click();
    CreateRosaWizardPage.addNodeLabelKeyAndValue(
      clusterFieldValidations.ClusterSettings.Machinepool.NodeLabel[0].UpperCharacterLimitValue,
      'test',
      0,
    );
    cy.get('span')
      .contains(clusterFieldValidations.ClusterSettings.Machinepool.NodeLabel[0].KeyError)
      .should('be.visible');
    cy.get('span')
      .contains(clusterFieldValidations.ClusterSettings.Machinepool.NodeLabel[0].LabelError)
      .should('not.exist');
    CreateRosaWizardPage.addNodeLabelKeyAndValue(
      'test',
      clusterFieldValidations.ClusterSettings.Machinepool.NodeLabel[0].UpperCharacterLimitValue,
      0,
    );
    cy.get('span')
      .contains(clusterFieldValidations.ClusterSettings.Machinepool.NodeLabel[0].KeyError)
      .should('not.exist');
    cy.get('span')
      .contains(clusterFieldValidations.ClusterSettings.Machinepool.NodeLabel[0].LabelError)
      .should('be.visible');
    CreateRosaWizardPage.addNodeLabelKeyAndValue('test-t_123.com', 'test-t_123.com', 0);
    cy.get('span')
      .contains(clusterFieldValidations.ClusterSettings.Machinepool.NodeLabel[0].KeyError)
      .should('not.exist');
    cy.get('span')
      .contains(clusterFieldValidations.ClusterSettings.Machinepool.NodeLabel[0].LabelError)
      .should('not.exist');

    CreateRosaWizardPage.addNodeLabelKeyAndValue(
      clusterFieldValidations.ClusterSettings.Machinepool.NodeLabel[1].InvalidValue,
      'test',
      0,
    );
    cy.get('span')
      .contains(clusterFieldValidations.ClusterSettings.Machinepool.NodeLabel[1].KeyError)
      .should('be.visible');
    CreateRosaWizardPage.addNodeLabelKeyAndValue(
      'testing',
      clusterFieldValidations.ClusterSettings.Machinepool.NodeLabel[1].InvalidValue,
      0,
    );
    cy.get('span')
      .contains(clusterFieldValidations.ClusterSettings.Machinepool.NodeLabel[1].LabelError)
      .should('be.visible');
    CreateRosaWizardPage.addNodeLabelKeyAndValue(
      clusterFieldValidations.ClusterSettings.Machinepool.NodeLabel[2].InvalidValue,
      'test',
      0,
    );
    cy.get('span')
      .contains(clusterFieldValidations.ClusterSettings.Machinepool.NodeLabel[2].KeyError)
      .should('be.visible');
    CreateRosaWizardPage.addNodeLabelKeyAndValue('example12-ing.com/MyName', 'test-ing_123.com', 0);
    cy.get('span')
      .contains(clusterFieldValidations.ClusterSettings.Machinepool.NodeLabel[0].KeyError)
      .should('not.exist');
    cy.get('span')
      .contains(clusterFieldValidations.ClusterSettings.Machinepool.NodeLabel[1].LabelError)
      .should('not.exist');
    cy.get('span')
      .contains(clusterFieldValidations.ClusterSettings.Machinepool.NodeLabel[1].KeyError)
      .should('not.exist');
    CreateRosaWizardPage.addAdditionalLabelLink().should('be.enabled');
    CreateRosaWizardPage.rosaNextButton().should('be.enabled');
    CreateRosaWizardPage.rosaBackButton().should('be.enabled');
    CreateRosaWizardPage.rosaCancelButton().should('be.enabled');
    CreateRosaWizardPage.rosaNextButton().click();
  });

  it('Step - Networking -  widget validations', () => {
    CreateRosaWizardPage.applicationIngressCustomSettingsRadio().check();
    CreateRosaWizardPage.applicationIngressRouterSelectorsInput()
      .clear()
      .type(
        clusterFieldValidations.Networking.Configuration.IngressSettings.CustomSettings
          .RouteSelector[0].UpperCharacterLimitValue,
      );
    cy.get('div')
      .contains(
        clusterFieldValidations.Networking.Configuration.IngressSettings.CustomSettings
          .RouteSelector[0].Error,
      )
      .should('be.visible');
    CreateRosaWizardPage.applicationIngressRouterSelectorsInput()
      .clear()
      .type(
        clusterFieldValidations.Networking.Configuration.IngressSettings.CustomSettings
          .RouteSelector[1].InvalidValue,
      );
    cy.get('div')
      .contains(
        clusterFieldValidations.Networking.Configuration.IngressSettings.CustomSettings
          .RouteSelector[1].Error,
      )
      .should('be.visible');
    CreateRosaWizardPage.applicationIngressRouterSelectorsInput()
      .clear()
      .type(
        clusterFieldValidations.Networking.Configuration.IngressSettings.CustomSettings
          .RouteSelector[2].InvalidValue,
      );
    cy.get('div')
      .contains(
        clusterFieldValidations.Networking.Configuration.IngressSettings.CustomSettings
          .RouteSelector[2].Error,
      )
      .should('be.visible');
    CreateRosaWizardPage.applicationIngressRouterSelectorsInput()
      .clear()
      .type(
        clusterFieldValidations.Networking.Configuration.IngressSettings.CustomSettings
          .RouteSelector[3].InvalidValue,
      );
    cy.get('div')
      .contains(
        clusterFieldValidations.Networking.Configuration.IngressSettings.CustomSettings
          .RouteSelector[3].Error,
      )
      .should('be.visible');
    CreateRosaWizardPage.applicationIngressRouterSelectorsInput()
      .clear()
      .type('valid123-k.com/Hello_world2');
    cy.get('div')
      .contains(
        clusterFieldValidations.Networking.Configuration.IngressSettings.CustomSettings
          .RouteSelector[0].Error,
      )
      .should('not.exist');
    CreateRosaWizardPage.applicationIngressExcludedNamespacesInput()
      .clear()
      .type(
        clusterFieldValidations.Networking.Configuration.IngressSettings.CustomSettings
          .ExcludedNamespaces[0].UpperCharacterLimitValue,
      );
    cy.get('div')
      .contains(
        clusterFieldValidations.Networking.Configuration.IngressSettings.CustomSettings
          .ExcludedNamespaces[0].Error,
      )
      .should('be.visible');
    CreateRosaWizardPage.applicationIngressExcludedNamespacesInput()
      .clear()
      .type(
        clusterFieldValidations.Networking.Configuration.IngressSettings.CustomSettings
          .ExcludedNamespaces[1].InvalidValue,
      );
    cy.get('div')
      .contains(
        clusterFieldValidations.Networking.Configuration.IngressSettings.CustomSettings
          .ExcludedNamespaces[1].Error,
      )
      .should('be.visible');
    CreateRosaWizardPage.applicationIngressExcludedNamespacesInput().clear().type('abc-123');
    cy.get('div')
      .contains(
        clusterFieldValidations.Networking.Configuration.IngressSettings.CustomSettings
          .ExcludedNamespaces[1].Error,
      )
      .should('not.exist');
    CreateRosaWizardPage.rosaNextButton().click();
  });

  it('Step - Networking - CIDR Ranges -  widget validations', () => {
    CreateRosaWizardPage.useCIDRDefaultValues(false);
    CreateRosaWizardPage.machineCIDRInput()
      .clear()
      .type(clusterFieldValidations.Networking.CIDRRanges.Common[0].Value);
    CreateRosaWizardPage.rosaNextButton().click();
    cy.get('div')
      .contains(clusterFieldValidations.Networking.CIDRRanges.Common[0].Error)
      .should('be.visible');
    CreateRosaWizardPage.machineCIDRInput()
      .clear()
      .type(clusterFieldValidations.Networking.CIDRRanges.Common[1].Value);
    CreateRosaWizardPage.rosaNextButton().click();
    cy.get('div')
      .contains(clusterFieldValidations.Networking.CIDRRanges.Common[1].Error)
      .should('be.visible');
    CreateRosaWizardPage.machineCIDRInput()
      .clear()
      .type(clusterFieldValidations.Networking.CIDRRanges.Common[2].Value);
    CreateRosaWizardPage.rosaNextButton().click();
    cy.get('div')
      .contains(clusterFieldValidations.Networking.CIDRRanges.Common[2].Error)
      .should('be.visible');
    CreateRosaWizardPage.machineCIDRInput().clear().type('10.0.0.0/16');
    cy.get('div')
      .contains(clusterFieldValidations.Networking.CIDRRanges.Common[2].Error)
      .should('not.exist');
    CreateRosaWizardPage.serviceCIDRInput()
      .clear()
      .type(clusterFieldValidations.Networking.CIDRRanges.Common[0].Value);
    CreateRosaWizardPage.rosaNextButton().click();
    cy.get('div')
      .contains(clusterFieldValidations.Networking.CIDRRanges.Common[0].Error)
      .should('be.visible');
    CreateRosaWizardPage.serviceCIDRInput()
      .clear()
      .type(clusterFieldValidations.Networking.CIDRRanges.Common[1].Value);
    CreateRosaWizardPage.rosaNextButton().click();
    cy.get('div')
      .contains(clusterFieldValidations.Networking.CIDRRanges.Common[1].Error)
      .should('be.visible');
    CreateRosaWizardPage.serviceCIDRInput()
      .clear()
      .type(clusterFieldValidations.Networking.CIDRRanges.Common[2].Value);
    CreateRosaWizardPage.rosaNextButton().click();
    cy.get('div')
      .contains(clusterFieldValidations.Networking.CIDRRanges.Common[2].Error)
      .should('be.visible');
    CreateRosaWizardPage.serviceCIDRInput().clear().type('172.30.0.0/16');
    cy.get('div')
      .contains(clusterFieldValidations.Networking.CIDRRanges.Common[2].Error)
      .should('not.exist');
    CreateRosaWizardPage.podCIDRInput()
      .clear()
      .type(clusterFieldValidations.Networking.CIDRRanges.Common[0].Value);
    CreateRosaWizardPage.rosaNextButton().click();
    cy.get('div')
      .contains(clusterFieldValidations.Networking.CIDRRanges.Common[0].Error)
      .should('be.visible');
    CreateRosaWizardPage.podCIDRInput()
      .clear()
      .type(clusterFieldValidations.Networking.CIDRRanges.Common[1].Value);
    CreateRosaWizardPage.rosaNextButton().click();
    cy.get('div')
      .contains(clusterFieldValidations.Networking.CIDRRanges.Common[1].Error)
      .should('be.visible');
    CreateRosaWizardPage.podCIDRInput()
      .clear()
      .type(clusterFieldValidations.Networking.CIDRRanges.Common[2].Value);
    CreateRosaWizardPage.rosaNextButton().click();
    cy.get('div')
      .contains(clusterFieldValidations.Networking.CIDRRanges.Common[2].Error)
      .should('be.visible');
    CreateRosaWizardPage.podCIDRInput().clear().type('10.128.0.0/16');
    cy.get('div')
      .contains(clusterFieldValidations.Networking.CIDRRanges.Common[2].Error)
      .should('not.exist');
    CreateRosaWizardPage.hostPrefixInput().clear();
    cy.get('div').contains('Field is required').should('be.visible');
    CreateRosaWizardPage.hostPrefixInput()
      .clear()
      .type(clusterFieldValidations.Networking.CIDRRanges.HostPrefix[0].Value);
    CreateRosaWizardPage.rosaNextButton().click();
    cy.get('div')
      .contains(clusterFieldValidations.Networking.CIDRRanges.HostPrefix[0].Error)
      .should('be.visible');
    CreateRosaWizardPage.hostPrefixInput()
      .clear()
      .type(clusterFieldValidations.Networking.CIDRRanges.HostPrefix[1].Value);
    CreateRosaWizardPage.rosaNextButton().click();
    cy.get('div')
      .contains(clusterFieldValidations.Networking.CIDRRanges.HostPrefix[1].Error)
      .should('be.visible');
    CreateRosaWizardPage.hostPrefixInput()
      .clear()
      .type(clusterFieldValidations.Networking.CIDRRanges.HostPrefix[2].Value);
    CreateRosaWizardPage.rosaNextButton().click();
    cy.get('div')
      .contains(clusterFieldValidations.Networking.CIDRRanges.HostPrefix[2].Error)
      .should('be.visible');
    CreateRosaWizardPage.hostPrefixInput().clear().type('/23');
    cy.get('div')
      .contains(clusterFieldValidations.Networking.CIDRRanges.HostPrefix[2].Error)
      .should('not.exist');
    CreateRosaWizardPage.useCIDRDefaultValues(true);
    CreateRosaWizardPage.rosaNextButton().click();
  });

  it('Step - Cluster roles and policies - widget validations', () => {
    CreateRosaWizardPage.customOperatorPrefixInput()
      .scrollIntoView()
      .type('{selectAll}')
      .type(
        clusterFieldValidations.ClusterRolesAndPolicies.OperatorRoles[0].UpperCharacterLimitValue,
      );
    CreateRosaWizardPage.rosaNextButton().click();
    cy.get('div')
      .contains(clusterFieldValidations.ClusterRolesAndPolicies.OperatorRoles[0].Error)
      .should('be.visible');
    CreateRosaWizardPage.customOperatorPrefixInput()
      .scrollIntoView()
      .type('{selectAll}')
      .type(clusterFieldValidations.ClusterRolesAndPolicies.OperatorRoles[1].InvalidValue);
    CreateRosaWizardPage.rosaNextButton().click();
    cy.get('div')
      .contains(clusterFieldValidations.ClusterRolesAndPolicies.OperatorRoles[1].Error)
      .should('be.visible');
    CreateRosaWizardPage.customOperatorPrefixInput()
      .scrollIntoView()
      .type('{selectAll}')
      .type('test-123-test');
    CreateRosaWizardPage.rosaNextButton().click();
  });
});
