export const GET_MACHINE_POOLS = 'GET_MACHINE_POOLS';
export const DELETE_MACHINE_POOL = 'DELETE_MACHINE_POOL';
export const CLEAR_GET_MACHINE_POOLS_RESPONSE = 'CLEAR_GET_MACHINE_POOLS_RESPONSE';
export const CLEAR_DELETE_MACHINE_POOL_RESPONSE = 'CLEAR_DELETE_MACHINE_POOL_RESPONSE';
