const GET_CLUSTER_ROUTERS = 'GET_CLUSTER_ROUTERS';
const EDIT_CLUSTER_ROUTERS = 'EDIT_CLUSTER_ROUTER';
const RESET_EDIT_ROUTERS_RESPONSE = 'RESET_EDIT_ROUTERS_RESPONSE';
const RESET_CLUSTER_ROUTERS = 'RESET_CLUSTER_ROUTERS';

const networkingConstants = {
  GET_CLUSTER_ROUTERS,
  EDIT_CLUSTER_ROUTERS,
  RESET_EDIT_ROUTERS_RESPONSE,
  RESET_CLUSTER_ROUTERS,
};

export {
  networkingConstants,
  GET_CLUSTER_ROUTERS,
  EDIT_CLUSTER_ROUTERS,
  RESET_EDIT_ROUTERS_RESPONSE,
  RESET_CLUSTER_ROUTERS,
};
