= OpenShift Cluster Manager

This repository contains the UI components for the OpenShift Cluster Manager site.

The UI is a pure JavaScript application written in React and Redux. Additionally it
contains a helper development server, `backend`, written in Go.

Building the Go backend requires checking out this repo in the correct place under GOPATH:

....
git clone https://gitlab.cee.redhat.com/service/uhc-portal $GOPATH/src/gitlab.cee.redhat.com/service/uhc-portal
# OR (clones into same place)
go get -d gitlab.cee.redhat.com/service/uhc-portal/...
....

If you don't have GOPATH set, you can pick any directory e.g.:

....
mkdir $HOME/go
export GOPATH=$HOME/go
....

== Style

To promote consistency in the code base and prevent bike-shedding over style
issues, OCM follows the JavaScript and React style guides produced by airbnb.

https://github.com/airbnb/javascript[airbnb style guides]

To guide and aid developers in style consistency, OCM uses eslint and the eslint
tools provided by airbnb.

https://eslint.org/[eslint]
https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb[airbnb eslint tools]

To run the linter

....
$ yarn lint
....

=== Local Linting

To use eslint tools locally (e.g. as part of your editor config), you may
need to follow the installation and usage instructions using global
installation.

https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb#eslint-config-airbnb-1[Installation instructions]

== Bulding

To build the application install the `yarn` tool and then run these commands:

....
$ yarn install
$ yarn build
....

To build the `backend` proxy server run the `binary` target of the _Makefile_:

....
$ make binary
....

Reminder: for this and most other Makefile targets, you need this directory in the right place under GOPATH.

== Testing

To test the application in your development environment run the following command:

....
$ yarn start
....

That will start the the Webpack development server. See below for instructions regarding the "chromed environment".

You will also need to start start the backend proxy server, which acts as a proxy
for the _OpenID_ and API services that are required by the application. Before
starting it make sure to have an offline access token, either in the `UHC_TOKEN`
environment variable or in the `token` parameter of the configuration file:

....
export UHC_TOKEN="eyJ..."
./backend
....

To obtain the access token go to the
https://cloud.redhat.com/openshift/token[token page] and copy the
_offline access token_.

By default the backend proxy server will be available at http://localhost:8002,
and the default configuration of the application is already prepared to use it.

If you need to change the configuration used by this backend proxy, then create a
YAML file and specify it with the `--config` command line option:

....
./backend --config=my.yml
....

The content of this file should be something like this (or any subset of it):

[source,yaml]
----
listener:
  address: localhost:8002

keycloak:
  url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
  client_id: cloud-services
  client_secret: # empty by default

proxies:
- prefix: /api/
  target: https://api.stage.openshift.com

token: eyJ...
----

Note that this `--config` option and the configuration file are optional, the
default configuration already uses `localhost`, `sso.redhat.com` and port
`8002`, and already forwards all API requests to the staging environment.

If you need to use a service located in some other place, for example if you
need to use the clusters service deployed in your local environment, you can add
an additional proxy configuration:

[source,yaml]
----
proxies:
- prefix: /api/clusters_mgmt/
  target: https://api.127.0.0.1.nip.io
----

That will forward requests starting with `/api/clusters_mgmt/` to your local
clusters service, and the rest to the staging environment.

=== Testing Without a Real Backend
Sometimes the backend might be broken, but you still want to develop the UI. For this purpose we've created
a basic mock server that sends mock data. It doesn't support all actions the real backend supports, but
it should allow you to run the UI and test basic read-only functionality.

To run it, run `mockdata/mockserver.py`.

Then in another terminal, run `yarn startmock` instead of `yarn start`, and you'll get a working UI showing mock data.

=== Chromed application
Start by cloning https://github.com/RedHatInsights/insights-proxy[insights-proxy] and following its setup instructions.

....
git clone https://github.com/RedHatInsights/insights-proxy.git
cd insights-proxy
sudo bash scripts/patch-etc-hosts.sh
bash scripts/update.sh
....

This is a one-time setup process. After this process is done, make sure to export the
location of your proxy's git clone to the PROXY_PATH environment variable, for example

....
export PROXY_PATH=~/Projects/insights-proxy
....

It's a good idea to add this line to your '~/.bashrc file' so you don't have to type it each time.

Make sure to start the backend proxy server (./backend) before starting the insights proxy.

Now you can use
....
SPANDX_CONFIG="./profiles/local-frontend.js" bash $PROXY_PATH/scripts/run.sh
....
to run the insights proxy and pass API requests to the mock server described above.

Run webpack with
....
$ yarn build; yarn start
....
The "build" step is crucial at the moment, but we should work to make it not required in the future.

Once the server is running you can access your UI on https://qa.foo.redhat.com:1337/openshift
It should ask you to authenticate with QA SSO, which should accept every user and the password is "redhat"

=== Chromed application with a mock server
Perform the exact steps detailed above, but use
....
mockdata/mockserver.py
....
instead of the backend proxy.

== Deploying

The staging and production OCM sites are deployed into the Insights enviroments
using the `push_to_insights.sh` script. This script is called via git hooks. See
the script for more details.
