= OpenShift Unified Hybrid Cloud

This repository contains the UI components for the OpenShift Unified Hybrid
Cloud site.

== Style

To promote consistency in the code base and prevent bike-shedding over style
issues, UHC follows the JavaScript and React style guides produced by airbnb.

https://github.com/airbnb/javascript[airbnb style guides]

To guide and aid developers in style consistency, UHC uses eslint and the eslint
tools provided by airbnb.

https://eslint.org/[eslint]
https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb[airbnb eslint tools]

To run the linter

....
$ yarn lint
....

=== Local Linting

To use eslint tools locally (e.g. as part of your editor config), you may
need to follow the installation and usage instructions using global
installation.

https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb#eslint-config-airbnb-1[Installation instructions]

== Bulding

To build the application install the `yarn` tool and then run these commands:

....
$ yarn install
$ yarn build
....

To build the backend proxy server run the `binary` target of the _Makefile_:

....
$ make binary
....

== Testing

To test the application in your development environment run the following command:

....
$ yarn start
....

That will start the the Webpack development server, in http://localhost:8001.

You will also need to start start the backend proxy server, which acts as a proxy
for the _OpenID_ and API services that are required by the application:

....
./backend
....

By default this will be available in http://localhost:8002, and the default
configuration of the application is already prepared to use it.

If you need to change the configuration used by this backend proxy, then create a
YAML file and specify it with the `--config` commmand line option:

....
./backend --config=my.yml
....

The content of this file should be something like this:

[source,yaml]
----
listener:
  address: localhost:8002

proxies:
- prefix: /api/
  target: https://api.stage.openshift.com
----

Note that this `--config` option and the configuration file are optional, the
default configuration already uses `localhost` and port `8002`, and already
forwards all API requests to the staging environment.

If you need to use a service located in some other place, for example if you
need to use the clusters service deployed in your local environment, you can add
an additional proxy configuration:

[source,yaml]
----
proxies:
- prefix: /api/clusters_mgmt/
  target: https://api.127.0.0.1.nip.io
----

That will forward requests starting with `/api/clusters_mgmt/` to your local
clusters service, and the rest to the staging environment.

== Deploying

In order to deploy the application to an _OpenShift_ cluster first you need to
build the image:

....
$ make image
....

As the image isn't currently uploaded to any image repository, you will need
then to save it to a `tar` file:

....
$ make tar
....

That will generate the `openshift-unified-hybrid-cloud_portal_latest.tar`. You
need to manually copy it to the nodes of the cluster where you want to deploy
the application, and load it into the docker daemon of the node. For example,
assuming that the name of the node is `sandbox` and that you have configured SSH
access without password, you can use the `scp` and `ssh` commands:

....
$ scp openshift-unified-hybrid-cloud_portal_latest.tar sandbox:
$ ssh sadnbox docker load -i openshift-unified-hybrid-cloud_portal_latest.tar
....

Once the image is loaded, you can run `deploy` target of the `Makefile` that
processes the `template.yml` template and creates all the required _OpenShift_
objects:

....
$ make deploy
....

That will create a `unified-hybrid-cloud` namespace, and inside that namespace a
`portal-server` deployment. Check that it is running:

....
$ oc project unified-hybrid-cloud
$ oc get pods
NAME                            READY STATUS  RESTARTS AGE
portal-server-c7664975c-sx6rr   1/1   Running 0        54m
....

A route for the `cloud.127.0.0.1.nip.io` DNS domain will also be created. So you
can go with your browser to https://cloud.127.0.0.1.nip.ip, and you should see
the application running. To do so you can use the `route.yml` file, and the
following command:

....
$ oc create -f route.yml
....
