/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export enum host_validation_id {
    CONNECTED = 'connected',
    MEDIA_CONNECTED = 'media-connected',
    HAS_INVENTORY = 'has-inventory',
    HAS_MIN_CPU_CORES = 'has-min-cpu-cores',
    HAS_MIN_VALID_DISKS = 'has-min-valid-disks',
    HAS_MIN_MEMORY = 'has-min-memory',
    MACHINE_CIDR_DEFINED = 'machine-cidr-defined',
    HAS_CPU_CORES_FOR_ROLE = 'has-cpu-cores-for-role',
    HAS_MEMORY_FOR_ROLE = 'has-memory-for-role',
    HOSTNAME_UNIQUE = 'hostname-unique',
    HOSTNAME_VALID = 'hostname-valid',
    BELONGS_TO_MACHINE_CIDR = 'belongs-to-machine-cidr',
    IGNITION_DOWNLOADABLE = 'ignition-downloadable',
    BELONGS_TO_MAJORITY_GROUP = 'belongs-to-majority-group',
    VALID_PLATFORM_NETWORK_SETTINGS = 'valid-platform-network-settings',
    NTP_SYNCED = 'ntp-synced',
    CONTAINER_IMAGES_AVAILABLE = 'container-images-available',
    LSO_REQUIREMENTS_SATISFIED = 'lso-requirements-satisfied',
    OCS_REQUIREMENTS_SATISFIED = 'ocs-requirements-satisfied',
    ODF_REQUIREMENTS_SATISFIED = 'odf-requirements-satisfied',
    SUFFICIENT_INSTALLATION_DISK_SPEED = 'sufficient-installation-disk-speed',
    CNV_REQUIREMENTS_SATISFIED = 'cnv-requirements-satisfied',
    SUFFICIENT_NETWORK_LATENCY_REQUIREMENT_FOR_ROLE = 'sufficient-network-latency-requirement-for-role',
    SUFFICIENT_PACKET_LOSS_REQUIREMENT_FOR_ROLE = 'sufficient-packet-loss-requirement-for-role',
    HAS_DEFAULT_ROUTE = 'has-default-route',
    API_DOMAIN_NAME_RESOLVED_CORRECTLY = 'api-domain-name-resolved-correctly',
    API_INT_DOMAIN_NAME_RESOLVED_CORRECTLY = 'api-int-domain-name-resolved-correctly',
    APPS_DOMAIN_NAME_RESOLVED_CORRECTLY = 'apps-domain-name-resolved-correctly',
    COMPATIBLE_WITH_CLUSTER_PLATFORM = 'compatible-with-cluster-platform',
    DNS_WILDCARD_NOT_CONFIGURED = 'dns-wildcard-not-configured',
    DISK_ENCRYPTION_REQUIREMENTS_SATISFIED = 'disk-encryption-requirements-satisfied',
    NON_OVERLAPPING_SUBNETS = 'non-overlapping-subnets',
    VSPHERE_DISK_UUID_ENABLED = 'vsphere-disk-uuid-enabled',
}
