const GET_USERS = 'GET_USERS';
const GET_CLUSTER_ADMINS = 'GET_CLUSTER_ADMINS';
const GET_DEDICATED_ADMNIS = 'GET_DEDICATED_ADMNIS';
const ADD_USER = 'ADD_USER';
const DELETE_USER = 'DELETE_USER';
const CLEAR_USER_RESPONSES = 'CLEAR_USER_RESPONSES';
const CLEAR_ADD_USER_RESPONSES = 'CLEAR_ADD_USER_RESPONSES';

const UsersConstants = {
  GET_USERS,
  GET_CLUSTER_ADMINS,
  GET_DEDICATED_ADMNIS,
  DELETE_USER,
  ADD_USER,
  CLEAR_USER_RESPONSES,
  CLEAR_ADD_USER_RESPONSES,
};

export default UsersConstants;
