const GET_ALERTS = 'GET_ALERTS';
const GET_NODES = 'GET_NODES';
const GET_OPERATORS = 'GET_OPERATORS';
const CLEAR_MONITORING_STATE = 'CLEAR_MONITORING_STATE';

const monitoringConstants = {
  GET_ALERTS,
  GET_NODES,
  GET_OPERATORS,
  CLEAR_MONITORING_STATE,
};

export { monitoringConstants, GET_ALERTS, GET_NODES };
