const GET_CLUSTER_IDENTITY_PROVIDERS = 'GET_CLUSTER_IDENTITY_PROVIDERS';
const CREATE_CLUSTER_IDENTITY_PROVIDER = 'CREATE_CLUSTER_IDENTITY_PROVIDER';
const RESET_CREATED_CLUSTER_IDP_RESPONSE = 'RESET_CREATED_CLUSTER_IDP_RESPONSE';

const identityProvidersConstants = {
  GET_CLUSTER_IDENTITY_PROVIDERS,
  CREATE_CLUSTER_IDENTITY_PROVIDER,
  RESET_CREATED_CLUSTER_IDP_RESPONSE,
};

export {
  identityProvidersConstants,
  GET_CLUSTER_IDENTITY_PROVIDERS,
  CREATE_CLUSTER_IDENTITY_PROVIDER,
  RESET_CREATED_CLUSTER_IDP_RESPONSE,
};
