import React from 'react';
import { useField, useFormikContext } from 'formik';

import { Alert, Content, Stack, StackItem, Title } from '@patternfly/react-core';

import links from '~/common/installLinks.mjs';
import { CheckboxField, TextInputField } from '~/components/clusters/wizards/form';
import { FieldId } from '~/components/clusters/wizards/rosa/constants';
import ExternalLink from '~/components/common/ExternalLink';

import { LogForwardingGroupsApplicationsSelector } from './LogForwardingGroupsApplicationsSelector';
import { createCloudWatchLogGroupName } from './logForwardingNaming';
import {
  cloudWatchLogGroupTooltip,
  cloudWatchRoleArnTooltip,
  groupsApplicationsAvailableTooltip,
  groupsApplicationsChosenTooltip,
} from './logForwardingTooltips';

export function CloudWatchLogForwarding() {
  const { setFieldValue, setFieldTouched } = useFormikContext<Record<string, unknown>>();
  const [{ value: cwEnabled }] = useField<boolean>(FieldId.LogForwardingCloudWatchEnabled);
  const [{ value: logGroupName }] = useField<string>(FieldId.LogForwardingCloudWatchLogGroupName);
  const [{ value: clusterNameRaw }] = useField<string>(FieldId.ClusterName);
  const clusterName = String(clusterNameRaw ?? '').trim();

  // Autofill is handled here in the event handler rather than a useEffect because
  // both actions are caused by a specific user interaction (toggling the checkbox), not by the
  // component being displayed. This keeps the data flow explicit and avoids the extra render
  // pass that a useEffect-based approach would introduce.
  //
  // Passing `onChange` via the `input` prop replaces CheckboxField's internal field.onChange,
  // so we call setFieldValue and setFieldTouched directly to replicate that behavior.
  function handleCwEnabledChange(_event: React.FormEvent<HTMLInputElement>, enabled: boolean) {
    setFieldValue(FieldId.LogForwardingCloudWatchEnabled, enabled);
    setFieldTouched(FieldId.LogForwardingCloudWatchEnabled, true, true);
    if (enabled && !logGroupName) {
      setFieldValue(
        FieldId.LogForwardingCloudWatchLogGroupName,
        createCloudWatchLogGroupName(clusterName),
      );
    }
  }

  return (
    <Stack hasGutter>
      <StackItem>
        <Title headingLevel="h4">CloudWatch</Title>
      </StackItem>
      <StackItem>
        <CheckboxField
          name={FieldId.LogForwardingCloudWatchEnabled}
          label="Enable CloudWatch"
          helperText="Used for real-time monitoring and analysis"
          input={{ onChange: handleCwEnabledChange }}
        />
      </StackItem>
      {cwEnabled ? (
        <StackItem>
          <Stack hasGutter>
            <StackItem>
              <Alert variant="info" isInline title="Prerequisite">
                <Stack hasGutter>
                  <StackItem>
                    <Content component="p">
                      To use a CloudWatch log group, you must create an IAM role and policy.{' '}
                      <ExternalLink href={links.LOG_FORWARDING_DOCS}>Learn more</ExternalLink>
                    </Content>
                  </StackItem>
                  <StackItem>
                    <CheckboxField
                      name={FieldId.LogForwardingCloudWatchPrerequisiteAck}
                      label="I've read and completed all the prerequisites and am ready to continue creating my cluster."
                    />
                  </StackItem>
                </Stack>
              </Alert>
            </StackItem>
            <StackItem>
              <TextInputField
                name={FieldId.LogForwardingCloudWatchLogGroupName}
                label="Log group name"
                formGroup={{ isRequired: true }}
                tooltip={cloudWatchLogGroupTooltip}
                helperText="Use the autogenerated name, or provide a custom one"
              />
            </StackItem>
            <StackItem>
              <TextInputField
                name={FieldId.LogForwardingCloudWatchRoleArn}
                label="Role ARN"
                formGroup={{ isRequired: true }}
                tooltip={cloudWatchRoleArnTooltip}
              />
            </StackItem>
            <StackItem>
              <LogForwardingGroupsApplicationsSelector
                name={FieldId.LogForwardingCloudWatchSelectedItems}
                isRequired
                availableTooltip={groupsApplicationsAvailableTooltip}
                chosenTooltip={groupsApplicationsChosenTooltip}
              />
            </StackItem>
          </Stack>
        </StackItem>
      ) : null}
    </Stack>
  );
}
