/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/upgrades_info/graph': {
    parameters: {
      query: {
        channel: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get the update graph */
    get: operations['getGraph'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/upgrades_info/v1/graph': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get the update graph */
    get: operations['getV1Graph'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Graph: {
      nodes?: components['schemas']['Node'][];
      edges?: components['schemas']['Edge'][];
    };
    Node: {
      version: string;
      payload: string;
      metadata: {
        [key: string]: string;
      };
    };
    Edge: number[];
    GraphError: {
      kind: string;
      value: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type Graph = components['schemas']['Graph'];
export type Node = components['schemas']['Node'];
export type Edge = components['schemas']['Edge'];
export type GraphError = components['schemas']['GraphError'];
export type $defs = Record<string, never>;
export interface operations {
  getGraph: {
    parameters: {
      query: {
        channel: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description An update graph */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Graph'];
        };
      };
      /** @description Bad client request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GraphError'];
        };
      };
      /** @description Invalid Content-Type */
      406: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GraphError'];
        };
      };
      /** @description Internal error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GraphError'];
        };
      };
      /** @description Generic graph error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GraphError'];
        };
      };
    };
  };
  getV1Graph: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description An update graph */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Graph'];
        };
      };
      /** @description Bad client request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GraphError'];
        };
      };
      /** @description Invalid Content-Type */
      406: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GraphError'];
        };
      };
      /** @description Internal error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GraphError'];
        };
      };
      /** @description Generic graph error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GraphError'];
        };
      };
    };
  };
}
