const DELETE_CLUSTER = 'DELETE_CLUSTER';
const CLEAR_DELETE_CLUSTER_RESPONSE = 'CLEAR_DELETE_CLUSTER_RESPONSE';

const deleteClusterDialogConstants = {
  DELETE_CLUSTER,
  CLEAR_DELETE_CLUSTER_RESPONSE,
};

export { deleteClusterDialogConstants, DELETE_CLUSTER, CLEAR_DELETE_CLUSTER_RESPONSE };
