export default {
  values: {
    hypershift: 'true',
    cloud_provider: 'aws',
    product: 'ROSA',
    byoc: 'true',
    billing_account_id: '123456789012',
    associated_aws_id: '210987654321',
    installer_role_arn: 'arn:aws:iam::210987654321:role/DTSTG-Installer-Role',
    support_role_arn: 'arn:aws:iam::210987654321:role/DTSTG-Support-Role',
    worker_role_arn: 'arn:aws:iam::210987654321:role/DTSTG-Worker-Role',
    rosa_max_os_version: '4.13',
    node_drain_grace_period: 60,
    upgrade_policy: 'manual',
    automatic_upgrade_schedule: '0 0 * * 0',
    multi_az: 'false',
    persistent_storage: '107374182400',
    load_balancers: '0',
    nodes_compute: 2,
    node_labels: [{}],
    name: 'my-cluster',
    dns_base_domain: '',
    aws_access_key_id: '',
    aws_secret_access_key: '',
    network_configuration_toggle: 'basic',
    cluster_privacy: 'internal',
    install_to_vpc: true,
    use_privatelink: true,
    configure_proxy: false,
    disable_scp_checks: false,
    billing_model: 'marketplace-aws',
    imds: 'optional',
    enable_user_workload_monitoring: 'true',
    region: 'us-west-2',
    az_0: 'Select availability zone',
    cluster_privacy_public_subnet: {
      subnet_id: '',
      availability_zone: '',
    },
    customer_managed_key: 'false',
    cluster_version: {
      kind: 'Version',
      id: 'openshift-v4.13.5',
      href: '/api/clusters_mgmt/v1/versions/openshift-v4.13.5',
      raw_id: '4.13.5',
      enabled: true,
      default: false,
      channel_group: 'stable',
      rosa_enabled: true,
      hosted_control_plane_enabled: true,
      end_of_life_timestamp: '2024-09-17T00:00:00Z',
    },
    custom_operator_roles_prefix: 'my-cluster-cu1f',
    selected_vpc_id: 'vpc-0cf6c1b4e2a234863',
    shared_vpc: { is_allowed: false },
    machine_pools_subnets: [
      {
        subnet_id: 'subnet-03e91a20f67277c7a',
        name: 'Public subnet',
        public: false,
        availability_zone: 'us-west-2a',
      },
    ],
    machine_type: 'm5.xlarge',
    cidr_default_values_toggle: true,
    network_machine_cidr: '10.0.0.0/16',
    network_service_cidr: '172.30.0.0/16',
    network_pod_cidr: '10.128.0.0/16',
    network_host_prefix: '/23',
    detected_ocm_role: true,
    rosa_roles_provider_creation_mode: 'manual',
    rosa_creator_arn: 'arn:aws:iam::210987654321:role/DTSTG-OCM-Role-15212158',
    byo_oidc_config_id: 'my_oidc_config_id',
    byo_oidc_config_id_managed: 'true',
    detected_ocm_and_user_roles: true,
  },
};
