/* tslint:disable */
/* eslint-disable */
/**
 * Babylon Hybrid Cloud Console API
 * API for integration of Babylon with the Red Hat Hybrid Cloud Console
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DemoExperienceDeploymentDetails } from './demo-experience-deployment-details';
import { DemoExperienceQuota } from './demo-experience-quota';
/**
 *
 * @export
 * @interface DemoExperience
 */
export interface DemoExperience {
  /**
   *
   * @type {DemoExperienceDeploymentDetails}
   * @memberof DemoExperience
   */
  deployment_details?: DemoExperienceDeploymentDetails;
  /**
   * URL of deployed experience. Only set if status is \"started\".
   * @type {string}
   * @memberof DemoExperience
   */
  experience_url?: string;
  /**
   *
   * @type {DemoExperienceQuota}
   * @memberof DemoExperience
   */
  quota?: DemoExperienceQuota;
  /**
   * Time when the demo experience was requested. Set if status is \"deploying\", \"started\", or \"failed\"
   * @type {Date}
   * @memberof DemoExperience
   */
  requested_timestamp?: Date;
  /**
   * Time when the demo experience will automatically delete.
   * @type {Date}
   * @memberof DemoExperience
   */
  scheduled_delete_timestamp?: Date;
  /**
   * Estimated time when demo experience will reach status of \"started\" in ISO 8601 UTC date and time format. Set if status is \"deploying\".
   * @type {Date}
   * @memberof DemoExperience
   */
  started_time_estimate?: Date;
  /**
   * Time when the demo experience started. Set if status is \"started\"
   * @type {Date}
   * @memberof DemoExperience
   */
  started_timestamp?: Date;
  /**
   * Status of demo experience which is one of:  \"available\" - Demo experience is available upon request. \"deploying\" - Demo experience has been requested and is deploying. Details in \"deployment\". \"started\" - Demo experience has been requested and successfully finished deploying. \"failed\" - Demo experience has been requested but failed somehow in deployment. \"unavailable\" - Demo experience is not available. Details in \"unavailable_reason\".
   * @type {string}
   * @memberof DemoExperience
   */
  status: DemoExperienceStatusEnum;
  /**
   * Short explanation of why demo experience is unavailable. Only set if status is \"unavailable\".
   * @type {string}
   * @memberof DemoExperience
   */
  unavailable_reason?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum DemoExperienceStatusEnum {
  Available = 'available',
  Deploying = 'deploying',
  Failed = 'failed',
  Started = 'started',
  Unavailable = 'unavailable',
  Requested = 'requested',
}
