/* tslint:disable */
/* eslint-disable */
/**
 * Babylon Hybrid Cloud Console API
 * API for integration of Babylon with the Red Hat Hybrid Cloud Console
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Quota that limits the number of demo experiences for the user.
 * @export
 * @interface DemoExperienceQuota
 */
export interface DemoExperienceQuota {
  /**
   * Current quota consumption for user.
   * @type {number}
   * @memberof DemoExperienceQuota
   */
  current: number;
  /**
   * Quota limit for user.
   * @type {number}
   * @memberof DemoExperienceQuota
   */
  limit: number;
}
