/* tslint:disable */
/* eslint-disable */
/**
 * Babylon Hybrid Cloud Console API
 * API for integration of Babylon with the Red Hat Hybrid Cloud Console
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Details of deployment status. Set if status is one of \"deploying\", \"started\", or \"failed\".
 * @export
 * @interface DemoExperienceDeploymentDetails
 */
export interface DemoExperienceDeploymentDetails {
  /**
   * Message describing why the deployment failed.
   * @type {string}
   * @memberof DemoExperienceDeploymentDetails
   */
  error_message?: string;
  /**
   * Detailed status string provided by deployment system.
   * @type {any}
   * @memberof DemoExperienceDeploymentDetails
   */
  status?: any;
}
