/* tslint:disable */
/* eslint-disable */
/**
 * Babylon Hybrid Cloud Console API
 * API for integration of Babylon with the Red Hat Hybrid Cloud Console
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface HealthCheck
 */
export interface HealthCheck {
  /**
   *
   * @type {string}
   * @memberof HealthCheck
   */
  status?: HealthCheckStatusEnum;
  /**
   *
   * @type {string}
   * @memberof HealthCheck
   */
  message?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum HealthCheckStatusEnum {
  Ok = 'ok',
  Error = 'error',
}
