/* tslint:disable */
/* eslint-disable */
/**
 * Babylon Hybrid Cloud Console API
 * API for integration of Babylon with the Red Hat Hybrid Cloud Console
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ModelError
 */
export interface ModelError {
  /**
   * Error code
   * @type {number}
   * @memberof ModelError
   */
  code: number;
  /**
   * Error message
   * @type {string}
   * @memberof ModelError
   */
  message: string;
}
