# this is the K8S frontend deployment descriptor used for containerized builds
# it was created following console-dot's containerized-FE migration guide:
# https://consoledot.pages.redhat.com/docs/dev/containerized-frontends/migration/migration.html#_step_5_create_the_frontend_resource_yaml

# yaml-language-server: $schema=https://raw.githubusercontent.com/RedHatInsights/frontend-components/refs/heads/master/packages/config-utils/src/feo/spec/frontend-crd.schema.json

apiVersion: v1
kind: Template
metadata:
  name: openshift
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: openshift
    spec:
      feoConfigEnabled: true
      envName: ${ENV_NAME}
      title: OCM UI
      deploymentRepo: https://github.com/RedHatInsights/uhc-portal
      API:
        versions:
          - v1
      frontend:
        paths:
          - /apps/openshift
      image: ${IMAGE}:${IMAGE_TAG}
      # navItems:
      #   - appId: "openshift"
      #     title: "Clusters"
      #     href: "/openshift"
      #     product: "Red Hat OpenShift Cluster Manager"
      bundleSegments:
        - segmentId: openshift
          bundleId: openshift
          position: 100
          navItems: 
            - id: overview
              title: Overview
              href: /openshift/overview
              product: Red Hat OpenShift Cluster Manager
            - id: cluster-management
              groupId: cluster-management
              title: Cluster Management
              navItems:
                - id: dashboard
                  title: Dashboard
                  href: /openshift/dashboard
                  product: Red Hat OpenShift Cluster Manager
                - id: clusters
                  title: Cluster List
                  href: /openshift/cluster-list
                  product: Red Hat OpenShift Cluster Manager
                - id: advisor
                  title: Advisor
                  expandable: true
                  routes:
                    - id: recommendations
                      title: Recommendations
                      href: /openshift/insights/advisor/recommendations
                      product: Red Hat OpenShift Cluster Manager
                    - id: advisor-clusters
                      title: Clusters
                      href: /openshift/insights/advisor/clusters
                      product: Red Hat OpenShift Cluster Manager
                    - id: workloads
                      title: Workloads
                      href: /openshift/insights/advisor/workloads
                      product: Red Hat OpenShift Cluster Manager
                      permissions:
                        - method: featureFlag
                          args: ["ocp-advisor-ui-workloads", true]
                        - method: featureFlag
                          args: ["ocp-advisor-workloads-release", true]
                - id: vulnerability-dashboard
                  title: Vulnerability Dashboard
                  expandable: true
                  routes:
                    - id: cves
                      title: CVEs
                      href: /openshift/insights/vulnerability/cves
                      product: Red Hat OpenShift Cluster Manager
                    - id: vulnerability-clusters
                      title: Clusters
                      href: /openshift/insights/vulnerability/clusters
                      product: Red Hat OpenShift Cluster Manager
                - id: subscriptions
                  title: Subscriptions
                  expandable: true
                  routes:
                    - id: subscriptions-usage
                      title: OpenShift Usage
                      href: /subscriptions/usage/openshift
                    - id: annual-subscriptions
                      title: Annual Subscriptions
                      href: /openshift/quota
                - id: cost-management
                  title: Cost Management
                  expandable: true
                  routes:
                    - id: cost-management-overview
                      title: Overview
                      href: /openshift/cost-management
                      product: Red Hat Cost Management
                    - id: systems
                      title: Systems
                      href: /openshift/cost-management/systems
                      product: Red Hat Cost Management
                      permissions:
                        - method: featureFlag
                          args: ["cost-management.ui.systems", true]
                    - id: cost-management-optimizations
                      title: Optimizations
                      href: /openshift/cost-management/optimizations
                      product: Red Hat Cost Management
                    - id: cost-management-openshift
                      title: Openshift
                      href: /openshift/cost-management/ocp
                      product: Red Hat Cost Management
                    - id: amazon-web-services
                      title: Amazon Web Services
                      href: /openshift/cost-management/aws
                      product: Red Hat Cost Management
                    - id: google-cloud-platform
                      title: Google Cloud Platform
                      href: /openshift/cost-management/gcp
                      product: Red Hat Cost Management
                    - id: microsoft-azure
                      title: Microsoft Azure
                      href: /openshift/cost-management/azure
                      product: Red Hat Cost Management
                    - id: cost-explorer
                      title: Cost Explorer
                      href: /openshift/cost-management/explorer
                      product: Red Hat Cost Management
                    - id: settings
                      title: Settings
                      href: /openshift/cost-management/settings
                      product: Red Hat Cost Management
            - id: products
              groupId: products
              title: Products
              navItems:
                - id: acm
                  title: Advanced Cluster Management
                  href: https://catalog.redhat.com/software/container-stacks/detail/5ec54aa3535cb70ab8c02996
                  isExternal: true
                - id: acs-section
                  title: Advanced Cluster Security
                  expandable: true
                  routes:
                    - id: clusterOverview
                      title: Overview
                      href: /openshift/acs/overview
                    - id: acs-getting-started
                      title: Getting Started
                      href: /openshift/acs/getting-started 
                    - id: acs-instances
                      title: ACS Instances
                      href: /openshift/acs/instances
                    - id: clusters-documentation
                      title: Documentation
                      href: https://docs.redhat.com/en/documentation/red_hat_advanced_cluster_security_for_kubernetes
                      isExternal: true
                - id: openshift-ai
                  title: OpenShift AI
                  expandable: true
                  routes:
                    - id: developer-sandbox-trial
                      title: Developer Sandbox | OpenShift AI
                      href: /openshift/sandbox
                    - id: sixty-day-trial
                      title: 60-Day Product Trial | OpenShift AI
                      href: https://www.redhat.com/en/technologies/cloud-computing/openshift/openshift-ai/trial
                      isExternal: true
                - id: openshift-virtualization
                  title: OpenShift Virtualization
                  href: https://catalog.redhat.com/software/container-stacks/detail/5ec53f218b6f188e53644c4f
                  isExternal: true
                - id: operators
                  title: Operators
                  href: /openshift/overview#recommended-operators
      module:
        manifestLocation: "/apps/openshift/fed-mods.json"
        moduleConfig:
          ssoScopes:
            - rhfull
        modules:
          - id: "openshift"
            module: "./RootApp"
            routes:
              - pathname: /openshift
parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/app-sre/uhc-portal
