const TOGGLE_SUBSCRIPTION_RELEASED = 'TOGGLE_SUBSCRIPTION_RELEASED';
const CLEAR_TOGGLE_SUBSCRIPTION_RELEASED_RESPONSE = 'CLEAR_TOGGLE_SUBSCRIPTION_RELEASED_RESPONSE';

export { TOGGLE_SUBSCRIPTION_RELEASED, CLEAR_TOGGLE_SUBSCRIPTION_RELEASED_RESPONSE };
