const LIST_ASSOCIATED_AWS_IDS = 'LIST_ASSOCIATED_AWS_IDS';
const GET_AWS_ACCOUNT_ROLES_ARNS = 'GET_AWS_ACCOUNT_ROLES_ARNS';
const GET_OCM_ROLE = 'GET_OCM_ROLE';
const GET_USER_ROLE = 'GET_USER_ROLE';
const CLEAR_GET_AWS_ACCOUNT_IDS_RESPONSE = 'CLEAR_GET_AWS_ACCOUNT_IDS_RESPONSE';
const CLEAR_GET_AWS_ACCOUNT_ROLES_ARNS_RESPONSE = 'CLEAR_GET_AWS_ACCOUNT_ROLES_ARNS_RESPONSE';
const CLEAR_GET_OCM_ROLE_RESPONSE = 'CLEAR_GET_OCM_ROLE_RESPONSE';
const CLEAR_GET_USER_ROLE_RESPONSE = 'CLEAR_GET_USER_ROLE_RESPONSE';
const SET_OFFLINE_TOKEN = 'SET_OFFLINE_TOKEN';
const LIST_USER_OIDC_CONFIGURATIONS = 'LIST_USER_OIDC_CONFIGURATIONS';
const MIN_MANAGED_POLICY_VERSION = 4.11;

export {
  LIST_ASSOCIATED_AWS_IDS,
  GET_AWS_ACCOUNT_ROLES_ARNS,
  GET_OCM_ROLE,
  GET_USER_ROLE,
  CLEAR_GET_AWS_ACCOUNT_IDS_RESPONSE,
  CLEAR_GET_AWS_ACCOUNT_ROLES_ARNS_RESPONSE,
  CLEAR_GET_OCM_ROLE_RESPONSE,
  CLEAR_GET_USER_ROLE_RESPONSE,
  SET_OFFLINE_TOKEN,
  LIST_USER_OIDC_CONFIGURATIONS,
  MIN_MANAGED_POLICY_VERSION,
};
