const LIST_ASSOCIATED_AWS_IDS = 'LIST_ASSOCIATED_AWS_IDS';
const GET_AWS_ACCOUNT_ROLES_ARNS = 'GET_AWS_ACCOUNT_ROLES_ARNS';
const CLEAR_GET_AWS_ACCOUNT_IDS_RESPONSE = 'CLEAR_GET_AWS_ACCOUNT_IDS_RESPONSE';
const CLEAR_GET_AWS_ACCOUNT_ROLES_ARNS_RESPONSE = 'CLEAR_GET_AWS_ACCOUNT_ROLES_ARNS_RESPONSE';

export {
  LIST_ASSOCIATED_AWS_IDS,
  GET_AWS_ACCOUNT_ROLES_ARNS,
  CLEAR_GET_AWS_ACCOUNT_IDS_RESPONSE,
  CLEAR_GET_AWS_ACCOUNT_ROLES_ARNS_RESPONSE,
};
