const LIST_ASSOCIATED_AWS_IDS = 'LIST_ASSOCIATED_AWS_IDS';
const GET_AWS_ACCOUNT_ROLES_ARNS = 'GET_AWS_ACCOUNT_ROLES_ARNS';
const GET_OCM_ROLE = 'GET_OCM_ROLE';
const GET_USER_ROLE = 'GET_USER_ROLE';
const CLEAR_GET_AWS_ACCOUNT_IDS_RESPONSE = 'CLEAR_GET_AWS_ACCOUNT_IDS_RESPONSE';
const CLEAR_GET_AWS_ACCOUNT_ROLES_ARNS_RESPONSE = 'CLEAR_GET_AWS_ACCOUNT_ROLES_ARNS_RESPONSE';
const CLEAR_GET_OCM_ROLE_RESPONSE = 'CLEAR_GET_OCM_ROLE_RESPONSE';
const CLEAR_GET_USER_ROLE_RESPONSE = 'CLEAR_GET_USER_ROLE_RESPONSE';

export {
  LIST_ASSOCIATED_AWS_IDS,
  GET_AWS_ACCOUNT_ROLES_ARNS,
  GET_OCM_ROLE,
  GET_USER_ROLE,
  CLEAR_GET_AWS_ACCOUNT_IDS_RESPONSE,
  CLEAR_GET_AWS_ACCOUNT_ROLES_ARNS_RESPONSE,
  CLEAR_GET_OCM_ROLE_RESPONSE,
  CLEAR_GET_USER_ROLE_RESPONSE,
};
