const GET_ADDONS = 'GET_ADDONS';
const GET_CLUSTER_ADDONS = 'GET_CLUSTER_ADDONS';
const ADD_CLUSTER_ADDON = 'ADD_CLUSTER_ADDON';
const CLEAR_CLUSTER_ADDON_RESPONSES = 'CLEAR_CLUSTER_ADDON_RESPONSES';

const AddOnsConstants = {
  GET_ADDONS,
  GET_CLUSTER_ADDONS,
  ADD_CLUSTER_ADDON,
  CLEAR_CLUSTER_ADDON_RESPONSES,
  INSTALLATION_STATE: {
    PENDING: 'pending',
    INSTALLING: 'installing',
    DELETING: 'deleting',
    FAILED: 'failed',
    READY: 'ready',
  },
};

export default AddOnsConstants;
