const GET_ADDONS = 'GET_ADDONS';
const GET_CLUSTER_ADDONS = 'GET_CLUSTER_ADDONS';
const ADD_CLUSTER_ADDON = 'ADD_CLUSTER_ADDON';
const CLEAR_ADDON_RESPONSES = 'CLEAR_ADDON_RESPONSES';

const AddOnsConstants = {
  GET_ADDONS,
  GET_CLUSTER_ADDONS,
  ADD_CLUSTER_ADDON,
  CLEAR_ADDON_RESPONSES,
};

export default AddOnsConstants;
