export default {
  githubReleases: {
    'openshift-online/ocm-cli': {
      error: false,
      pending: false,
      fulfilled: true,
      data: {
        url: 'https://api.github.com/repos/openshift-online/ocm-cli/releases/133445694',
        assets_url:
          'https://api.github.com/repos/openshift-online/ocm-cli/releases/133445694/assets',
        upload_url:
          'https://uploads.github.com/repos/openshift-online/ocm-cli/releases/133445694/assets{?name,label}',
        html_url: 'https://github.com/openshift-online/ocm-cli/releases/tag/v0.1.72',
        id: 133445694,
        author: {
          login: 'github-actions[bot]',
          id: 41898282,
          node_id: 'MDM6Qm90NDE4OTgyODI=',
          avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/github-actions%5Bbot%5D',
          html_url: 'https://github.com/apps/github-actions',
          followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
          following_url:
            'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
          gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
          starred_url:
            'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
          organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
          repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
          events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
          received_events_url:
            'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
          type: 'Bot',
          site_admin: false,
        },
        node_id: 'RE_kwDODDNgWs4H9Dg-',
        tag_name: 'v0.1.72',
        target_commitish: 'main',
        name: 'Release 0.1.72',
        draft: false,
        prerelease: false,
        created_at: '2023-12-11T16:44:48Z',
        published_at: '2023-12-11T16:50:39Z',
        assets: [
          {
            url: 'https://api.github.com/repos/openshift-online/ocm-cli/releases/assets/140110613',
            id: 140110613,
            node_id: 'RA_kwDODDNgWs4IWesV',
            name: 'ocm-darwin-amd64',
            label: '',
            uploader: {
              login: 'github-actions[bot]',
              id: 41898282,
              node_id: 'MDM6Qm90NDE4OTgyODI=',
              avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/github-actions%5Bbot%5D',
              html_url: 'https://github.com/apps/github-actions',
              followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
              following_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
              gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
              starred_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
              subscriptions_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
              organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
              repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
              events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
              received_events_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
              type: 'Bot',
              site_admin: false,
            },
            content_type: 'application/octet-stream',
            state: 'uploaded',
            size: 35696208,
            download_count: 14,
            created_at: '2023-12-11T16:50:46Z',
            updated_at: '2023-12-11T16:50:47Z',
            browser_download_url:
              'https://github.com/openshift-online/ocm-cli/releases/download/v0.1.72/ocm-darwin-amd64',
          },
          {
            url: 'https://api.github.com/repos/openshift-online/ocm-cli/releases/assets/140110609',
            id: 140110609,
            node_id: 'RA_kwDODDNgWs4IWesR',
            name: 'ocm-darwin-amd64.sha256',
            label: '',
            uploader: {
              login: 'github-actions[bot]',
              id: 41898282,
              node_id: 'MDM6Qm90NDE4OTgyODI=',
              avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/github-actions%5Bbot%5D',
              html_url: 'https://github.com/apps/github-actions',
              followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
              following_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
              gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
              starred_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
              subscriptions_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
              organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
              repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
              events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
              received_events_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
              type: 'Bot',
              site_admin: false,
            },
            content_type: 'application/octet-stream',
            state: 'uploaded',
            size: 83,
            download_count: 0,
            created_at: '2023-12-11T16:50:45Z',
            updated_at: '2023-12-11T16:50:45Z',
            browser_download_url:
              'https://github.com/openshift-online/ocm-cli/releases/download/v0.1.72/ocm-darwin-amd64.sha256',
          },
          {
            url: 'https://api.github.com/repos/openshift-online/ocm-cli/releases/assets/140110600',
            id: 140110600,
            node_id: 'RA_kwDODDNgWs4IWesI',
            name: 'ocm-darwin-arm64',
            label: '',
            uploader: {
              login: 'github-actions[bot]',
              id: 41898282,
              node_id: 'MDM6Qm90NDE4OTgyODI=',
              avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/github-actions%5Bbot%5D',
              html_url: 'https://github.com/apps/github-actions',
              followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
              following_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
              gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
              starred_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
              subscriptions_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
              organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
              repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
              events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
              received_events_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
              type: 'Bot',
              site_admin: false,
            },
            content_type: 'application/octet-stream',
            state: 'uploaded',
            size: 35429058,
            download_count: 7,
            created_at: '2023-12-11T16:50:39Z',
            updated_at: '2023-12-11T16:50:40Z',
            browser_download_url:
              'https://github.com/openshift-online/ocm-cli/releases/download/v0.1.72/ocm-darwin-arm64',
          },
          {
            url: 'https://api.github.com/repos/openshift-online/ocm-cli/releases/assets/140110605',
            id: 140110605,
            node_id: 'RA_kwDODDNgWs4IWesN',
            name: 'ocm-darwin-arm64.sha256',
            label: '',
            uploader: {
              login: 'github-actions[bot]',
              id: 41898282,
              node_id: 'MDM6Qm90NDE4OTgyODI=',
              avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/github-actions%5Bbot%5D',
              html_url: 'https://github.com/apps/github-actions',
              followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
              following_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
              gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
              starred_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
              subscriptions_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
              organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
              repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
              events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
              received_events_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
              type: 'Bot',
              site_admin: false,
            },
            content_type: 'application/octet-stream',
            state: 'uploaded',
            size: 83,
            download_count: 4,
            created_at: '2023-12-11T16:50:44Z',
            updated_at: '2023-12-11T16:50:44Z',
            browser_download_url:
              'https://github.com/openshift-online/ocm-cli/releases/download/v0.1.72/ocm-darwin-arm64.sha256',
          },
          {
            url: 'https://api.github.com/repos/openshift-online/ocm-cli/releases/assets/140110603',
            id: 140110603,
            node_id: 'RA_kwDODDNgWs4IWesL',
            name: 'ocm-linux-amd64',
            label: '',
            uploader: {
              login: 'github-actions[bot]',
              id: 41898282,
              node_id: 'MDM6Qm90NDE4OTgyODI=',
              avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/github-actions%5Bbot%5D',
              html_url: 'https://github.com/apps/github-actions',
              followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
              following_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
              gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
              starred_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
              subscriptions_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
              organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
              repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
              events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
              received_events_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
              type: 'Bot',
              site_admin: false,
            },
            content_type: 'application/octet-stream',
            state: 'uploaded',
            size: 35943339,
            download_count: 186,
            created_at: '2023-12-11T16:50:42Z',
            updated_at: '2023-12-11T16:50:43Z',
            browser_download_url:
              'https://github.com/openshift-online/ocm-cli/releases/download/v0.1.72/ocm-linux-amd64',
          },
          {
            url: 'https://api.github.com/repos/openshift-online/ocm-cli/releases/assets/140110604',
            id: 140110604,
            node_id: 'RA_kwDODDNgWs4IWesM',
            name: 'ocm-linux-amd64.sha256',
            label: '',
            uploader: {
              login: 'github-actions[bot]',
              id: 41898282,
              node_id: 'MDM6Qm90NDE4OTgyODI=',
              avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/github-actions%5Bbot%5D',
              html_url: 'https://github.com/apps/github-actions',
              followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
              following_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
              gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
              starred_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
              subscriptions_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
              organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
              repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
              events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
              received_events_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
              type: 'Bot',
              site_admin: false,
            },
            content_type: 'application/octet-stream',
            state: 'uploaded',
            size: 82,
            download_count: 52,
            created_at: '2023-12-11T16:50:44Z',
            updated_at: '2023-12-11T16:50:44Z',
            browser_download_url:
              'https://github.com/openshift-online/ocm-cli/releases/download/v0.1.72/ocm-linux-amd64.sha256',
          },
          {
            url: 'https://api.github.com/repos/openshift-online/ocm-cli/releases/assets/140110622',
            id: 140110622,
            node_id: 'RA_kwDODDNgWs4IWese',
            name: 'ocm-linux-arm64',
            label: '',
            uploader: {
              login: 'github-actions[bot]',
              id: 41898282,
              node_id: 'MDM6Qm90NDE4OTgyODI=',
              avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/github-actions%5Bbot%5D',
              html_url: 'https://github.com/apps/github-actions',
              followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
              following_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
              gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
              starred_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
              subscriptions_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
              organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
              repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
              events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
              received_events_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
              type: 'Bot',
              site_admin: false,
            },
            content_type: 'application/octet-stream',
            state: 'uploaded',
            size: 34985779,
            download_count: 2,
            created_at: '2023-12-11T16:50:50Z',
            updated_at: '2023-12-11T16:50:52Z',
            browser_download_url:
              'https://github.com/openshift-online/ocm-cli/releases/download/v0.1.72/ocm-linux-arm64',
          },
          {
            url: 'https://api.github.com/repos/openshift-online/ocm-cli/releases/assets/140110611',
            id: 140110611,
            node_id: 'RA_kwDODDNgWs4IWesT',
            name: 'ocm-linux-arm64.sha256',
            label: '',
            uploader: {
              login: 'github-actions[bot]',
              id: 41898282,
              node_id: 'MDM6Qm90NDE4OTgyODI=',
              avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/github-actions%5Bbot%5D',
              html_url: 'https://github.com/apps/github-actions',
              followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
              following_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
              gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
              starred_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
              subscriptions_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
              organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
              repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
              events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
              received_events_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
              type: 'Bot',
              site_admin: false,
            },
            content_type: 'application/octet-stream',
            state: 'uploaded',
            size: 82,
            download_count: 1,
            created_at: '2023-12-11T16:50:46Z',
            updated_at: '2023-12-11T16:50:46Z',
            browser_download_url:
              'https://github.com/openshift-online/ocm-cli/releases/download/v0.1.72/ocm-linux-arm64.sha256',
          },
          {
            url: 'https://api.github.com/repos/openshift-online/ocm-cli/releases/assets/140110602',
            id: 140110602,
            node_id: 'RA_kwDODDNgWs4IWesK',
            name: 'ocm-linux-ppc64le',
            label: '',
            uploader: {
              login: 'github-actions[bot]',
              id: 41898282,
              node_id: 'MDM6Qm90NDE4OTgyODI=',
              avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/github-actions%5Bbot%5D',
              html_url: 'https://github.com/apps/github-actions',
              followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
              following_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
              gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
              starred_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
              subscriptions_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
              organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
              repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
              events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
              received_events_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
              type: 'Bot',
              site_admin: false,
            },
            content_type: 'application/octet-stream',
            state: 'uploaded',
            size: 35418285,
            download_count: 0,
            created_at: '2023-12-11T16:50:41Z',
            updated_at: '2023-12-11T16:50:42Z',
            browser_download_url:
              'https://github.com/openshift-online/ocm-cli/releases/download/v0.1.72/ocm-linux-ppc64le',
          },
          {
            url: 'https://api.github.com/repos/openshift-online/ocm-cli/releases/assets/140110610',
            id: 140110610,
            node_id: 'RA_kwDODDNgWs4IWesS',
            name: 'ocm-linux-ppc64le.sha256',
            label: '',
            uploader: {
              login: 'github-actions[bot]',
              id: 41898282,
              node_id: 'MDM6Qm90NDE4OTgyODI=',
              avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/github-actions%5Bbot%5D',
              html_url: 'https://github.com/apps/github-actions',
              followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
              following_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
              gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
              starred_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
              subscriptions_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
              organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
              repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
              events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
              received_events_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
              type: 'Bot',
              site_admin: false,
            },
            content_type: 'application/octet-stream',
            state: 'uploaded',
            size: 84,
            download_count: 0,
            created_at: '2023-12-11T16:50:45Z',
            updated_at: '2023-12-11T16:50:46Z',
            browser_download_url:
              'https://github.com/openshift-online/ocm-cli/releases/download/v0.1.72/ocm-linux-ppc64le.sha256',
          },
          {
            url: 'https://api.github.com/repos/openshift-online/ocm-cli/releases/assets/140110615',
            id: 140110615,
            node_id: 'RA_kwDODDNgWs4IWesX',
            name: 'ocm-linux-s390x',
            label: '',
            uploader: {
              login: 'github-actions[bot]',
              id: 41898282,
              node_id: 'MDM6Qm90NDE4OTgyODI=',
              avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/github-actions%5Bbot%5D',
              html_url: 'https://github.com/apps/github-actions',
              followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
              following_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
              gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
              starred_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
              subscriptions_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
              organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
              repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
              events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
              received_events_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
              type: 'Bot',
              site_admin: false,
            },
            content_type: 'application/octet-stream',
            state: 'uploaded',
            size: 36962442,
            download_count: 0,
            created_at: '2023-12-11T16:50:48Z',
            updated_at: '2023-12-11T16:50:50Z',
            browser_download_url:
              'https://github.com/openshift-online/ocm-cli/releases/download/v0.1.72/ocm-linux-s390x',
          },
          {
            url: 'https://api.github.com/repos/openshift-online/ocm-cli/releases/assets/140110614',
            id: 140110614,
            node_id: 'RA_kwDODDNgWs4IWesW',
            name: 'ocm-linux-s390x.sha256',
            label: '',
            uploader: {
              login: 'github-actions[bot]',
              id: 41898282,
              node_id: 'MDM6Qm90NDE4OTgyODI=',
              avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/github-actions%5Bbot%5D',
              html_url: 'https://github.com/apps/github-actions',
              followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
              following_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
              gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
              starred_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
              subscriptions_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
              organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
              repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
              events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
              received_events_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
              type: 'Bot',
              site_admin: false,
            },
            content_type: 'application/octet-stream',
            state: 'uploaded',
            size: 82,
            download_count: 0,
            created_at: '2023-12-11T16:50:48Z',
            updated_at: '2023-12-11T16:50:48Z',
            browser_download_url:
              'https://github.com/openshift-online/ocm-cli/releases/download/v0.1.72/ocm-linux-s390x.sha256',
          },
          {
            url: 'https://api.github.com/repos/openshift-online/ocm-cli/releases/assets/140110625',
            id: 140110625,
            node_id: 'RA_kwDODDNgWs4IWesh',
            name: 'ocm-windows-amd64',
            label: '',
            uploader: {
              login: 'github-actions[bot]',
              id: 41898282,
              node_id: 'MDM6Qm90NDE4OTgyODI=',
              avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/github-actions%5Bbot%5D',
              html_url: 'https://github.com/apps/github-actions',
              followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
              following_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
              gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
              starred_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
              subscriptions_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
              organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
              repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
              events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
              received_events_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
              type: 'Bot',
              site_admin: false,
            },
            content_type: 'application/octet-stream',
            state: 'uploaded',
            size: 36116480,
            download_count: 12,
            created_at: '2023-12-11T16:50:52Z',
            updated_at: '2023-12-11T16:50:53Z',
            browser_download_url:
              'https://github.com/openshift-online/ocm-cli/releases/download/v0.1.72/ocm-windows-amd64',
          },
          {
            url: 'https://api.github.com/repos/openshift-online/ocm-cli/releases/assets/140110618',
            id: 140110618,
            node_id: 'RA_kwDODDNgWs4IWesa',
            name: 'ocm-windows-amd64.sha256',
            label: '',
            uploader: {
              login: 'github-actions[bot]',
              id: 41898282,
              node_id: 'MDM6Qm90NDE4OTgyODI=',
              avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/github-actions%5Bbot%5D',
              html_url: 'https://github.com/apps/github-actions',
              followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
              following_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
              gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
              starred_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
              subscriptions_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
              organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
              repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
              events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
              received_events_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
              type: 'Bot',
              site_admin: false,
            },
            content_type: 'application/octet-stream',
            state: 'uploaded',
            size: 84,
            download_count: 0,
            created_at: '2023-12-11T16:50:50Z',
            updated_at: '2023-12-11T16:50:50Z',
            browser_download_url:
              'https://github.com/openshift-online/ocm-cli/releases/download/v0.1.72/ocm-windows-amd64.sha256',
          },
        ],
        tarball_url: 'https://api.github.com/repos/openshift-online/ocm-cli/tarball/v0.1.72',
        zipball_url: 'https://api.github.com/repos/openshift-online/ocm-cli/zipball/v0.1.72',
        body: "\n- OCM-4960: Do not print expiration timestamp if not set\n- OCM-5131 | feat: add SG IDs to describe cluster and list machinepools\n- Add 'secure-boot-for-shielded-vms' flag to expose secureboot on GCP\n- OCM-5131 | fix: don't show additional compute SGs describing cluster\n\n",
      },
    },
    'redhat-developer/app-services-cli': {
      error: false,
      pending: false,
      fulfilled: true,
      data: {
        url: 'https://api.github.com/repos/redhat-developer/app-services-cli/releases/93427158',
        assets_url:
          'https://api.github.com/repos/redhat-developer/app-services-cli/releases/93427158/assets',
        upload_url:
          'https://uploads.github.com/repos/redhat-developer/app-services-cli/releases/93427158/assets{?name,label}',
        html_url: 'https://github.com/redhat-developer/app-services-cli/releases/tag/v0.53.0',
        id: 93427158,
        author: {
          login: 'jackdelahunt',
          id: 45426048,
          node_id: 'MDQ6VXNlcjQ1NDI2MDQ4',
          avatar_url: 'https://avatars.githubusercontent.com/u/45426048?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/jackdelahunt',
          html_url: 'https://github.com/jackdelahunt',
          followers_url: 'https://api.github.com/users/jackdelahunt/followers',
          following_url: 'https://api.github.com/users/jackdelahunt/following{/other_user}',
          gists_url: 'https://api.github.com/users/jackdelahunt/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/jackdelahunt/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/jackdelahunt/subscriptions',
          organizations_url: 'https://api.github.com/users/jackdelahunt/orgs',
          repos_url: 'https://api.github.com/users/jackdelahunt/repos',
          events_url: 'https://api.github.com/users/jackdelahunt/events{/privacy}',
          received_events_url: 'https://api.github.com/users/jackdelahunt/received_events',
          type: 'User',
          site_admin: false,
        },
        node_id: 'RE_kwDOEnafEs4FkZXW',
        tag_name: 'v0.53.0',
        target_commitish: 'main',
        name: '0.53.0',
        draft: false,
        prerelease: false,
        created_at: '2023-02-23T11:34:16Z',
        published_at: '2023-02-23T11:35:40Z',
        assets: [
          {
            url: 'https://api.github.com/repos/redhat-developer/app-services-cli/releases/assets/96791477',
            id: 96791477,
            node_id: 'RA_kwDOEnafEs4FxOu1',
            name: 'checksums.txt',
            label: '',
            uploader: {
              login: 'github-actions[bot]',
              id: 41898282,
              node_id: 'MDM6Qm90NDE4OTgyODI=',
              avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/github-actions%5Bbot%5D',
              html_url: 'https://github.com/apps/github-actions',
              followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
              following_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
              gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
              starred_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
              subscriptions_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
              organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
              repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
              events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
              received_events_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
              type: 'Bot',
              site_admin: false,
            },
            content_type: 'text/plain; charset=utf-8',
            state: 'uploaded',
            size: 869,
            download_count: 2,
            created_at: '2023-02-23T11:43:42Z',
            updated_at: '2023-02-23T11:43:43Z',
            browser_download_url:
              'https://github.com/redhat-developer/app-services-cli/releases/download/v0.53.0/checksums.txt',
          },
          {
            url: 'https://api.github.com/repos/redhat-developer/app-services-cli/releases/assets/96791467',
            id: 96791467,
            node_id: 'RA_kwDOEnafEs4FxOur',
            name: 'rhoas_0.53.0_linux_amd64.deb',
            label: '',
            uploader: {
              login: 'github-actions[bot]',
              id: 41898282,
              node_id: 'MDM6Qm90NDE4OTgyODI=',
              avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/github-actions%5Bbot%5D',
              html_url: 'https://github.com/apps/github-actions',
              followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
              following_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
              gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
              starred_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
              subscriptions_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
              organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
              repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
              events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
              received_events_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
              type: 'Bot',
              site_admin: false,
            },
            content_type: 'application/vnd.debian.binary-package',
            state: 'uploaded',
            size: 14092198,
            download_count: 2,
            created_at: '2023-02-23T11:43:41Z',
            updated_at: '2023-02-23T11:43:42Z',
            browser_download_url:
              'https://github.com/redhat-developer/app-services-cli/releases/download/v0.53.0/rhoas_0.53.0_linux_amd64.deb',
          },
          {
            url: 'https://api.github.com/repos/redhat-developer/app-services-cli/releases/assets/96791468',
            id: 96791468,
            node_id: 'RA_kwDOEnafEs4FxOus',
            name: 'rhoas_0.53.0_linux_amd64.rpm',
            label: '',
            uploader: {
              login: 'github-actions[bot]',
              id: 41898282,
              node_id: 'MDM6Qm90NDE4OTgyODI=',
              avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/github-actions%5Bbot%5D',
              html_url: 'https://github.com/apps/github-actions',
              followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
              following_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
              gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
              starred_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
              subscriptions_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
              organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
              repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
              events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
              received_events_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
              type: 'Bot',
              site_admin: false,
            },
            content_type: 'application/x-rpm',
            state: 'uploaded',
            size: 14059274,
            download_count: 5,
            created_at: '2023-02-23T11:43:41Z',
            updated_at: '2023-02-23T11:43:42Z',
            browser_download_url:
              'https://github.com/redhat-developer/app-services-cli/releases/download/v0.53.0/rhoas_0.53.0_linux_amd64.rpm',
          },
          {
            url: 'https://api.github.com/repos/redhat-developer/app-services-cli/releases/assets/96791456',
            id: 96791456,
            node_id: 'RA_kwDOEnafEs4FxOug',
            name: 'rhoas_0.53.0_linux_amd64.tar.gz',
            label: '',
            uploader: {
              login: 'github-actions[bot]',
              id: 41898282,
              node_id: 'MDM6Qm90NDE4OTgyODI=',
              avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/github-actions%5Bbot%5D',
              html_url: 'https://github.com/apps/github-actions',
              followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
              following_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
              gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
              starred_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
              subscriptions_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
              organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
              repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
              events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
              received_events_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
              type: 'Bot',
              site_admin: false,
            },
            content_type: 'application/gzip',
            state: 'uploaded',
            size: 13438152,
            download_count: 3936,
            created_at: '2023-02-23T11:43:37Z',
            updated_at: '2023-02-23T11:43:38Z',
            browser_download_url:
              'https://github.com/redhat-developer/app-services-cli/releases/download/v0.53.0/rhoas_0.53.0_linux_amd64.tar.gz',
          },
          {
            url: 'https://api.github.com/repos/redhat-developer/app-services-cli/releases/assets/96791465',
            id: 96791465,
            node_id: 'RA_kwDOEnafEs4FxOup',
            name: 'rhoas_0.53.0_linux_arm64.deb',
            label: '',
            uploader: {
              login: 'github-actions[bot]',
              id: 41898282,
              node_id: 'MDM6Qm90NDE4OTgyODI=',
              avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/github-actions%5Bbot%5D',
              html_url: 'https://github.com/apps/github-actions',
              followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
              following_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
              gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
              starred_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
              subscriptions_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
              organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
              repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
              events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
              received_events_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
              type: 'Bot',
              site_admin: false,
            },
            content_type: 'application/vnd.debian.binary-package',
            state: 'uploaded',
            size: 12667764,
            download_count: 3,
            created_at: '2023-02-23T11:43:40Z',
            updated_at: '2023-02-23T11:43:40Z',
            browser_download_url:
              'https://github.com/redhat-developer/app-services-cli/releases/download/v0.53.0/rhoas_0.53.0_linux_arm64.deb',
          },
          {
            url: 'https://api.github.com/repos/redhat-developer/app-services-cli/releases/assets/96791474',
            id: 96791474,
            node_id: 'RA_kwDOEnafEs4FxOuy',
            name: 'rhoas_0.53.0_linux_arm64.rpm',
            label: '',
            uploader: {
              login: 'github-actions[bot]',
              id: 41898282,
              node_id: 'MDM6Qm90NDE4OTgyODI=',
              avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/github-actions%5Bbot%5D',
              html_url: 'https://github.com/apps/github-actions',
              followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
              following_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
              gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
              starred_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
              subscriptions_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
              organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
              repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
              events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
              received_events_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
              type: 'Bot',
              site_admin: false,
            },
            content_type: 'application/x-rpm',
            state: 'uploaded',
            size: 12669474,
            download_count: 2,
            created_at: '2023-02-23T11:43:42Z',
            updated_at: '2023-02-23T11:43:43Z',
            browser_download_url:
              'https://github.com/redhat-developer/app-services-cli/releases/download/v0.53.0/rhoas_0.53.0_linux_arm64.rpm',
          },
          {
            url: 'https://api.github.com/repos/redhat-developer/app-services-cli/releases/assets/96791460',
            id: 96791460,
            node_id: 'RA_kwDOEnafEs4FxOuk',
            name: 'rhoas_0.53.0_linux_arm64.tar.gz',
            label: '',
            uploader: {
              login: 'github-actions[bot]',
              id: 41898282,
              node_id: 'MDM6Qm90NDE4OTgyODI=',
              avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/github-actions%5Bbot%5D',
              html_url: 'https://github.com/apps/github-actions',
              followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
              following_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
              gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
              starred_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
              subscriptions_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
              organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
              repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
              events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
              received_events_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
              type: 'Bot',
              site_admin: false,
            },
            content_type: 'application/gzip',
            state: 'uploaded',
            size: 12156175,
            download_count: 7,
            created_at: '2023-02-23T11:43:38Z',
            updated_at: '2023-02-23T11:43:39Z',
            browser_download_url:
              'https://github.com/redhat-developer/app-services-cli/releases/download/v0.53.0/rhoas_0.53.0_linux_arm64.tar.gz',
          },
          {
            url: 'https://api.github.com/repos/redhat-developer/app-services-cli/releases/assets/96791461',
            id: 96791461,
            node_id: 'RA_kwDOEnafEs4FxOul',
            name: 'rhoas_0.53.0_macOS_amd64.tar.gz',
            label: '',
            uploader: {
              login: 'github-actions[bot]',
              id: 41898282,
              node_id: 'MDM6Qm90NDE4OTgyODI=',
              avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/github-actions%5Bbot%5D',
              html_url: 'https://github.com/apps/github-actions',
              followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
              following_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
              gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
              starred_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
              subscriptions_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
              organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
              repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
              events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
              received_events_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
              type: 'Bot',
              site_admin: false,
            },
            content_type: 'application/gzip',
            state: 'uploaded',
            size: 14135743,
            download_count: 188,
            created_at: '2023-02-23T11:43:38Z',
            updated_at: '2023-02-23T11:43:39Z',
            browser_download_url:
              'https://github.com/redhat-developer/app-services-cli/releases/download/v0.53.0/rhoas_0.53.0_macOS_amd64.tar.gz',
          },
          {
            url: 'https://api.github.com/repos/redhat-developer/app-services-cli/releases/assets/96791457',
            id: 96791457,
            node_id: 'RA_kwDOEnafEs4FxOuh',
            name: 'rhoas_0.53.0_macOS_arm64.tar.gz',
            label: '',
            uploader: {
              login: 'github-actions[bot]',
              id: 41898282,
              node_id: 'MDM6Qm90NDE4OTgyODI=',
              avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/github-actions%5Bbot%5D',
              html_url: 'https://github.com/apps/github-actions',
              followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
              following_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
              gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
              starred_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
              subscriptions_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
              organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
              repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
              events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
              received_events_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
              type: 'Bot',
              site_admin: false,
            },
            content_type: 'application/gzip',
            state: 'uploaded',
            size: 13499707,
            download_count: 16,
            created_at: '2023-02-23T11:43:37Z',
            updated_at: '2023-02-23T11:43:38Z',
            browser_download_url:
              'https://github.com/redhat-developer/app-services-cli/releases/download/v0.53.0/rhoas_0.53.0_macOS_arm64.tar.gz',
          },
          {
            url: 'https://api.github.com/repos/redhat-developer/app-services-cli/releases/assets/96791464',
            id: 96791464,
            node_id: 'RA_kwDOEnafEs4FxOuo',
            name: 'rhoas_0.53.0_windows_amd64.zip',
            label: '',
            uploader: {
              login: 'github-actions[bot]',
              id: 41898282,
              node_id: 'MDM6Qm90NDE4OTgyODI=',
              avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/github-actions%5Bbot%5D',
              html_url: 'https://github.com/apps/github-actions',
              followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
              following_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
              gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
              starred_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
              subscriptions_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
              organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
              repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
              events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
              received_events_url:
                'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
              type: 'Bot',
              site_admin: false,
            },
            content_type: 'application/zip',
            state: 'uploaded',
            size: 13512525,
            download_count: 130,
            created_at: '2023-02-23T11:43:39Z',
            updated_at: '2023-02-23T11:43:40Z',
            browser_download_url:
              'https://github.com/redhat-developer/app-services-cli/releases/download/v0.53.0/rhoas_0.53.0_windows_amd64.zip',
          },
        ],
        tarball_url:
          'https://api.github.com/repos/redhat-developer/app-services-cli/tarball/v0.53.0',
        zipball_url:
          'https://api.github.com/repos/redhat-developer/app-services-cli/zipball/v0.53.0',
        body: "## What's Changed\r\n* refactor: override fetch if instance exists by @rkpattnaik780 in https://github.com/redhat-developer/app-services-cli/pull/1760\r\n* feat: now using core sdk by @jackdelahunt in https://github.com/redhat-developer/app-services-cli/pull/1813\r\n* fix(service-registry create): improve error handling by @rkpattnaik780 in https://github.com/redhat-developer/app-services-cli/pull/1814\r\n\r\n\r\n**Full Changelog**: https://github.com/redhat-developer/app-services-cli/compare/v0.52.2...v0.53.0",
        mentions_count: 2,
      },
    },
  },
};
