export const GET_CLUSTER_INSIGHTS = 'GET_CLUSTER_INSIGHTS';
export const VOTE_ON_RULE_INSIGHTS = 'VOTE_ON_RULE_INSIGHTS';
export const DISABLE_RULE_INSIGHTS = 'DISABLE_RULE_INSIGHTS';
export const ENABLE_RULE_INSIGHTS = 'ENABLE_RULE_INSIGHTS';
