const GET_OCM_ROLES = 'GET_OCM_ROLES';
const GRANT_OCM_ROLE = 'GRANT_OCM_ROLE';
const EDIT_OCM_ROLE = 'EDIT_OCM_ROLE';
const DELETE_OCM_ROLE = 'DELETE_OCM_ROLE';
const CLEAR_GET_OCM_ROLES_RESPONSE = 'CLEAR_GET_OCM_ROLES_RESPONSE';
const CLEAR_GRANT_OCM_ROLE_RESPONSE = 'CLEAR_GRANT_OCM_ROLE_RESPONSE';
const CLEAR_EDIT_OCM_ROLE_RESPONSE = 'CLEAR_EDIT_OCM_ROLE_RESPONSE';
const CLEAR_DELETE_OCM_ROLE_RESPONSE = 'CLEAR_DELETE_OCM_ROLE_RESPONSE';

const OCMRolesConstants = {
  GET_OCM_ROLES,
  GRANT_OCM_ROLE,
  EDIT_OCM_ROLE,
  DELETE_OCM_ROLE,
  CLEAR_GET_OCM_ROLES_RESPONSE,
  CLEAR_GRANT_OCM_ROLE_RESPONSE,
  CLEAR_EDIT_OCM_ROLE_RESPONSE,
  CLEAR_DELETE_OCM_ROLE_RESPONSE,
};

export default OCMRolesConstants;
