const GET_CLUSTER_IDENTITY_PROVIDERS = 'GET_CLUSTER_IDENTITY_PROVIDERS';
const CREATE_CLUSTER_IDENTITY_PROVIDER = 'CREATE_CLUSTER_IDENTITY_PROVIDER';
const RESET_CREATED_CLUSTER_IDP_RESPONSE = 'RESET_CREATED_CLUSTER_IDP_RESPONSE';
const DELETE_IDENTITY_PROVIDER = 'DELETE_IDENTITY_PROVIDER';
const RESET_DELETED_IDP_RESPONSE = 'RESET_DELETED_IDP_RESPONSE';
const RESET_IDENTITY_PROVIDERS_STATE = 'RESET_IDENTITY_PROVIDERS_STATE';
const UPDATE_CLUSTER_IDENTITY_PROVIDER = 'UPDATE_CLUSTER_IDENTITY_PROVIDER';

const identityProvidersConstants = {
  GET_CLUSTER_IDENTITY_PROVIDERS,
  CREATE_CLUSTER_IDENTITY_PROVIDER,
  RESET_CREATED_CLUSTER_IDP_RESPONSE,
  DELETE_IDENTITY_PROVIDER,
  RESET_DELETED_IDP_RESPONSE,
  RESET_IDENTITY_PROVIDERS_STATE,
  UPDATE_CLUSTER_IDENTITY_PROVIDER,
};

export {
  identityProvidersConstants,
  GET_CLUSTER_IDENTITY_PROVIDERS,
  CREATE_CLUSTER_IDENTITY_PROVIDER,
  RESET_CREATED_CLUSTER_IDP_RESPONSE,
  DELETE_IDENTITY_PROVIDER,
  RESET_DELETED_IDP_RESPONSE,
  RESET_IDENTITY_PROVIDERS_STATE,
  UPDATE_CLUSTER_IDENTITY_PROVIDER,
};
