/*
Copyright (c) 2018 Red Hat, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

const CLEAR_DISPLAY_NAME_RESPONSE = 'CLEAR_DISPLAY_NAME_RESPONSE'; // TODO: refactor this const
const CREATE_CLUSTER = 'CREATE_CLUSTER';
const EDIT_CLUSTER = 'EDIT_CLUSTER';
const ARCHIVE_CLUSTER = 'ARCHIVE_CLUSTER';
const CLEAR_CLUSTER_ARCHIVE_RESPONSE = 'CLEAR_CLUSTER_ARCHIVE_RESPONSE';
const UNARCHIVE_CLUSTER = 'UNARCHIVE_CLUSTER';
const CLEAR_CLUSTER_UNARCHIVE_RESPONSE = 'CLEAR_CLUSTER_UNARCHIVE_RESPONSE';
const GET_CLUSTERS = 'GET_CLUSTERS';
const GET_CLUSTERS_WITH_PARAMS = 'GET_CLUSTERS_WITH_PARAMS';
const GET_CLUSTER_DETAILS = 'GET_CLUSTER_DETAILS';
const SET_CLUSTER_DETAILS = 'SET_CLUSTER_DETAILS';
const RESET_CREATED_CLUSTER_RESPONSE = 'RESET_CREATED_CLUSTER_RESPONSE';
const GET_CLUSTER_STATUS = 'GET_CLUSTER_STATUS';
const GET_CLUSTER_VERSIONS = 'GET_CLUSTER_VERSIONS';
const GET_CLUSTER_AWS_ACCOUNT_ID = 'GET_CLUSTER_AWS_ACCOUNT_ID';
const HIBERNATE_CLUSTER = 'HIBERNATE_CLUSTER';
const CLEAR_CLUSTER_HIBERNATE_RESPONSE = 'CLEAR_CLUSTER_HIBERNATE_RESPONSE';
const RESUME_CLUSTER = 'RESUME_CLUSTER';
const CLEAR_RESUME_CLUSTER_RESPONSE = 'CLEAR_RESUME_CLUSTER_RESPONSE';
const UPGRADE_TRIAL_CLUSTER = 'UPGRADE_TRIAL_CLUSTER';
const CLEAR_UPGRADE_TRIAL_CLUSTER_RESPONSE = 'CLEAR_UPGRADE_TRIAL_CLUSTER_RESPONSE';
const GET_UPGRADE_GATES = 'GET_UPGRADE_GATES';
const GET_CLUSTER_UPGRADE_GATES = 'GET_CLUSTER_UPGRADE_GATES';
const SET_CLUSTER_UPGRADE_GATE = 'SET_CLUSTER_UPGRADE_GATE';

export {
  CLEAR_DISPLAY_NAME_RESPONSE,
  CREATE_CLUSTER,
  EDIT_CLUSTER,
  ARCHIVE_CLUSTER,
  CLEAR_CLUSTER_ARCHIVE_RESPONSE,
  HIBERNATE_CLUSTER,
  CLEAR_CLUSTER_HIBERNATE_RESPONSE,
  RESUME_CLUSTER,
  CLEAR_RESUME_CLUSTER_RESPONSE,
  UNARCHIVE_CLUSTER,
  CLEAR_CLUSTER_UNARCHIVE_RESPONSE,
  GET_CLUSTERS,
  GET_CLUSTERS_WITH_PARAMS,
  GET_CLUSTER_DETAILS,
  SET_CLUSTER_DETAILS,
  RESET_CREATED_CLUSTER_RESPONSE,
  GET_CLUSTER_STATUS,
  GET_CLUSTER_VERSIONS,
  GET_CLUSTER_AWS_ACCOUNT_ID,
  UPGRADE_TRIAL_CLUSTER,
  CLEAR_UPGRADE_TRIAL_CLUSTER_RESPONSE,
  GET_UPGRADE_GATES,
  GET_CLUSTER_UPGRADE_GATES,
  SET_CLUSTER_UPGRADE_GATE,
};
