const GET_CLUSTER_AUTOSCALER = 'GET_CLUSTER_AUTOSCALER'; // GET
const ENABLE_CLUSTER_AUTOSCALER = 'ENABLE_CLUSTER_AUTOSCALER'; // POST
const DISABLE_CLUSTER_AUTOSCALER = 'DISABLE_CLUSTER_AUTOSCALER'; // DELETE
const UPDATE_CLUSTER_AUTOSCALER = 'UPDATE_CLUSTER_AUTOSCALER'; // PATCH

const SET_HAS_INITIAL_AUTOSCALER = 'SET_HAS_INITIAL_AUTOSCALER';
const CLEAR_LAST_ACTION_RESULT = 'CLEAR_LAST_ACTION_RESULT';

export default GET_CLUSTER_AUTOSCALER;
export {
  GET_CLUSTER_AUTOSCALER,
  ENABLE_CLUSTER_AUTOSCALER,
  DISABLE_CLUSTER_AUTOSCALER,
  UPDATE_CLUSTER_AUTOSCALER,
  SET_HAS_INITIAL_AUTOSCALER,
  CLEAR_LAST_ACTION_RESULT,
};
