/*
Copyright (c) 2018 Red Hat, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

const CREATE_CLUSTER = 'CREATE_CLUSTER';
const EDIT_CLUSTER = 'EDIT_CLUSTER';
const GET_CLUSTERS = 'GET_CLUSTERS'; /*  ARCHIVED CODE - DO NOT USE */
const GET_CLUSTER_DETAILS = 'GET_CLUSTER_DETAILS';
const SET_CLUSTER_DETAILS = 'SET_CLUSTER_DETAILS';
const CLEAR_CLUSTER_DETAILS = 'CLEAR_CLUSTER_DETAILS';
const RESET_CREATED_CLUSTER_RESPONSE = 'RESET_CREATED_CLUSTER_RESPONSE';
const GET_INFLIGHT_CHECKS = 'GET_INFLIGHT_CHECKS';
const CLEAR_CLUSTER_VERSIONS_RESPONSE = 'CLEAR_CLUSTER_VERSIONS_RESPONSE';
const GET_CLUSTER_VERSIONS = 'GET_CLUSTER_VERSIONS';
const HIBERNATE_CLUSTER = 'HIBERNATE_CLUSTER';
const RESUME_CLUSTER = 'RESUME_CLUSTER';
const UPGRADE_TRIAL_CLUSTER = 'UPGRADE_TRIAL_CLUSTER';
const GET_UPGRADE_GATES = 'GET_UPGRADE_GATES';
const SET_CLUSTER_UPGRADE_GATE = 'SET_CLUSTER_UPGRADE_GATE';
const GET_TECH_PREVIEW = 'GET_TECH_PREVIEW';

export {
  CREATE_CLUSTER,
  EDIT_CLUSTER,
  HIBERNATE_CLUSTER,
  RESUME_CLUSTER,
  GET_CLUSTERS /* ARCHIVED CODE - DO NOT USE */,
  GET_CLUSTER_DETAILS,
  SET_CLUSTER_DETAILS,
  CLEAR_CLUSTER_DETAILS,
  RESET_CREATED_CLUSTER_RESPONSE,
  GET_INFLIGHT_CHECKS,
  CLEAR_CLUSTER_VERSIONS_RESPONSE,
  GET_CLUSTER_VERSIONS,
  UPGRADE_TRIAL_CLUSTER,
  GET_UPGRADE_GATES,
  SET_CLUSTER_UPGRADE_GATE,
  GET_TECH_PREVIEW,
};
