const GET_DNS_DOMAINS = 'GET_DNS_DOMAINS';
const CREATE_DNS_DOMAIN = 'CREATE_DNS_DOMAIN';
const DELETE_DNS_DOMAIN = 'DELETE_DNS_DOMAIN';
const CLEAR_CREATED_DNS_DOMAIN = 'CLEAR_CREATED_DNS_DOMAIN';

export { GET_DNS_DOMAINS, CREATE_DNS_DOMAIN, DELETE_DNS_DOMAIN, CLEAR_CREATED_DNS_DOMAIN };
