// Redux actions
const SET_FEATURE = 'SET_FEATURE';

// Internal ids for Unleash features: (see featureActions.js for corresponding Unleash ids)
const ASSISTED_INSTALLER_FEATURE = 'ASSISTED_INSTALLER_FEATURE';
const ASSISTED_INSTALLER_MERGE_LISTS_FEATURE = 'ASSISTED_INSTALLER_MERGE_LISTS_FEATURE';
const HYPERSHIFT_WIZARD_FEATURE = 'HYPERSHIFT_WIZARD_FEATURE';
const SECURITY_GROUPS_FEATURE = 'SECURITY_GROUPS_FEATURE';
const SECURITY_GROUPS_FEATURE_DAY1 = 'SECURITY_GROUPS_FEATURE_DAY1';
const OSD_GOOGLE_MARKETPLACE_FEATURE = 'OSD_GOOGLE_MARKETPLACE_FEATURE';
const OSD_GCP_SHARED_VPC_FEATURE = 'OSD_GCP_SHARED_VPC_FEATURE';
const NETWORK_VALIDATOR_ONDEMAND_FEATURE = 'NETWORK_VALIDATOR_ONDEMAND_FEATURE';
const HCP_ROSA_GETTING_STARTED_PAGE = 'HCP_ROSA_GETTING_STARTED_PAGE';
const HCP_USE_UNMANAGED = 'HCP_USE_UNMANAGED';
const HCP_USE_NODE_UPGRADE_POLICIES = 'HCP_USE_NODE_UPGRADE_POLICIES';
const ENABLE_MACHINE_CONFIGURATION = 'ENABLE_MACHINE_CONFIGURATION';
const CLI_SSO_AUTHORIZATION = 'CLI_SSO_AUTHORIZATION';
const MULTIREGION_PREVIEW_ENABLED = 'MULTIREGION_PREVIEW_ENABLED';
const ACCESS_REQUEST_ENABLED = 'ACCESS_REQUEST_ENABLED';
const LONGER_CLUSTER_NAME_UI = 'LONGER_CLUSTER_NAME_UI';
const CLUSTER_OWNERSHIP_TRANSFER = 'CLUSTER_OWNERSHIP_TRANSFER';
const OSD_GCP_WIF = 'OSD_GCP_WIF';
// Ids for custom action in featureActions.js
const ASSISTED_INSTALLER_PLATFORM_OCI = 'ASSISTED_INSTALLER_PLATFORM_OCI';

export {
  SET_FEATURE,
  ASSISTED_INSTALLER_PLATFORM_OCI,
  ASSISTED_INSTALLER_FEATURE,
  ASSISTED_INSTALLER_MERGE_LISTS_FEATURE,
  HYPERSHIFT_WIZARD_FEATURE,
  SECURITY_GROUPS_FEATURE,
  SECURITY_GROUPS_FEATURE_DAY1,
  OSD_GOOGLE_MARKETPLACE_FEATURE,
  OSD_GCP_SHARED_VPC_FEATURE,
  NETWORK_VALIDATOR_ONDEMAND_FEATURE,
  HCP_ROSA_GETTING_STARTED_PAGE,
  HCP_USE_UNMANAGED,
  HCP_USE_NODE_UPGRADE_POLICIES,
  ENABLE_MACHINE_CONFIGURATION,
  CLI_SSO_AUTHORIZATION,
  MULTIREGION_PREVIEW_ENABLED,
  ACCESS_REQUEST_ENABLED,
  LONGER_CLUSTER_NAME_UI,
  CLUSTER_OWNERSHIP_TRANSFER,
  OSD_GCP_WIF,
};
