const SET_FEATURE = 'SET_FEATURE';
const ASSISTED_INSTALLER_FEATURE = 'ASSISTED_INSTALLER_FEATURE';
const OSD_UPGRADES_FEATURE = 'OSD_UPGRADES_FEATURE';
const SUPPORT_TAB_FEATURE = 'SUPPORT_TAB_FEATURE';

export {
  SET_FEATURE,
  ASSISTED_INSTALLER_FEATURE,
  OSD_UPGRADES_FEATURE,
  SUPPORT_TAB_FEATURE,
};
