const SET_FEATURE = 'SET_FEATURE';
const ASSISTED_INSTALLER_FEATURE = 'ASSISTED_INSTALLER_FEATURE';
const ASSISTED_INSTALLER_SNO_FEATURE = 'ASSISTED_INSTALLER_SNO_FEATURE';
const ASSISTED_INSTALLER_OCS_FEATURE = 'ASSISTED_INSTALLER_OCS_FEATURE';
const ASSISTED_INSTALLER_CNV_FEATURE = 'ASSISTED_INSTALLER_CNV_FEATURE';
const OSD_TRIAL_FEATURE = 'OSD_TRIAL_FEATURE';

export {
  SET_FEATURE,
  ASSISTED_INSTALLER_FEATURE,
  ASSISTED_INSTALLER_SNO_FEATURE,
  ASSISTED_INSTALLER_OCS_FEATURE,
  ASSISTED_INSTALLER_CNV_FEATURE,
  OSD_TRIAL_FEATURE,
};
