// Redux actions
const SET_FEATURE = 'SET_FEATURE';

// Internal ids for Unleash features: (see featureActions.js for corresponding Unleash ids)
const HYPERSHIFT_WIZARD_FEATURE = 'HYPERSHIFT_WIZARD_FEATURE';
const HCP_USE_UNMANAGED = 'HCP_USE_UNMANAGED';
const ENABLE_MACHINE_CONFIGURATION = 'ENABLE_MACHINE_CONFIGURATION';
const CLI_SSO_AUTHORIZATION = 'CLI_SSO_AUTHORIZATION';
const MULTIREGION_PREVIEW_ENABLED = 'MULTIREGION_PREVIEW_ENABLED';
const CLUSTER_OWNERSHIP_TRANSFER = 'CLUSTER_OWNERSHIP_TRANSFER';
const UNSTABLE_CLUSTER_VERSIONS = 'UNSTABLE_CLUSTER_VERSIONS';
const MAX_COMPUTE_NODES_500 = 'MAX_COMPUTE_NODES_500';
const OSD_GCP_WIF = 'OSD_GCP_WIF';
const CREATE_CLUSTER_YAML_EDITOR = 'CREATE_CLUSTER_YAML_EDITOR';
const EDIT_BILLING_ACCOUNT = 'EDIT_BILLING_ACCOUNT';
const PRIVATE_SERVICE_CONNECT = 'PRIVATE_SERVICE_CONNECT';
const HCP_ROOT_DISK_SIZE = 'HCP_ROOT_DISK_SIZE';
const BYPASS_COMPUTE_NODE_COUNT_LIMIT_CLASSIC_OSD_GCP =
  'BYPASS_COMPUTE_NODE_COUNT_LIMIT_CLASSIC_OSD_GCP';
const OCMUI_MAX_NODES_TOTAL_249 = 'OCMUI_MAX_NODES_TOTAL_249';

export {
  SET_FEATURE,
  HYPERSHIFT_WIZARD_FEATURE,
  HCP_USE_UNMANAGED,
  ENABLE_MACHINE_CONFIGURATION,
  CLI_SSO_AUTHORIZATION,
  MULTIREGION_PREVIEW_ENABLED,
  CLUSTER_OWNERSHIP_TRANSFER,
  OSD_GCP_WIF,
  CREATE_CLUSTER_YAML_EDITOR,
  UNSTABLE_CLUSTER_VERSIONS,
  EDIT_BILLING_ACCOUNT,
  PRIVATE_SERVICE_CONNECT,
  MAX_COMPUTE_NODES_500,
  HCP_ROOT_DISK_SIZE,
  BYPASS_COMPUTE_NODE_COUNT_LIMIT_CLASSIC_OSD_GCP,
  OCMUI_MAX_NODES_TOTAL_249,
};
