// Redux actions
const SET_FEATURE = 'SET_FEATURE';

// Internal ids for Unleash features: (see featureActions.js for corresponding Unleash ids)
const ASSISTED_INSTALLER_SNO_FEATURE = 'ASSISTED_INSTALLER_SNO_FEATURE';
const ASSISTED_INSTALLER_OCS_FEATURE = 'ASSISTED_INSTALLER_OCS_FEATURE';
const ASSISTED_INSTALLER_CNV_FEATURE = 'ASSISTED_INSTALLER_CNV_FEATURE';
const ASSISTED_INSTALLER_MERGE_LISTS_FEATURE = 'ASSISTED_INSTALLER_MERGE_LISTS_FEATURE';
const HYPERSHIFT_WIZARD_FEATURE = 'HYPERSHIFT_WIZARD_FEATURE';
const OSD_GOOGLE_MARKETPLACE_FEATURE = 'OSD_GOOGLE_MARKETPLACE_FEATURE';
const OSD_GCP_SHARED_VPC_FEATURE = 'OSD_GCP_SHARED_VPC_FEATURE';
const HCP_ROSA_GETTING_STARTED_PAGE = 'HCP_ROSA_GETTING_STARTED_PAGE';
const HCP_AWS_BILLING_SHOW = 'HCP_AWS_BILLING_SHOW';
const HCP_AWS_BILLING_REQUIRED = 'HCP_AWS_BILLING_REQUIRED';
const HCP_USE_UNMANAGED = 'HCP_USE_UNMANAGED';

// Ids for custom action in featureActions.js
const ASSISTED_INSTALLER_FEATURE = 'ASSISTED_INSTALLER_FEATURE';
const ASSISTED_INSTALLER_PLATFORM_OCI = 'ASSISTED_INSTALLER_PLATFORM_OCI';

export {
  SET_FEATURE,
  ASSISTED_INSTALLER_PLATFORM_OCI,
  ASSISTED_INSTALLER_FEATURE,
  ASSISTED_INSTALLER_SNO_FEATURE,
  ASSISTED_INSTALLER_OCS_FEATURE,
  ASSISTED_INSTALLER_CNV_FEATURE,
  ASSISTED_INSTALLER_MERGE_LISTS_FEATURE,
  HYPERSHIFT_WIZARD_FEATURE,
  OSD_GOOGLE_MARKETPLACE_FEATURE,
  OSD_GCP_SHARED_VPC_FEATURE,
  HCP_ROSA_GETTING_STARTED_PAGE,
  HCP_AWS_BILLING_SHOW,
  HCP_AWS_BILLING_REQUIRED,
  HCP_USE_UNMANAGED,
};
