const GET_MACHINE_TYPES = 'GET_MACHINE_TYPES';
const GET_MACHINE_TYPES_BY_REGION = 'GET_MACHINE_TYPES_BY_REGION';

export default GET_MACHINE_TYPES;
export { GET_MACHINE_TYPES, GET_MACHINE_TYPES_BY_REGION };
