const GET_MACHINE_TYPES = 'GET_MACHINE_TYPES';
const GET_MACHINE_TYPES_BY_REGION = 'GET_MACHINE_TYPES_BY_REGION';
const RESET_INITIAL_STATE = 'RESET_INITIAL_STATE';

export default GET_MACHINE_TYPES;
export { GET_MACHINE_TYPES, GET_MACHINE_TYPES_BY_REGION, RESET_INITIAL_STATE };
