const EDIT_SUBSCRIPTION_SETTINGS = 'EDIT_SUBSCRIPTION_SETTINGS';
const CLEAR_EDIT_SUBSCRIPTION_SETTINGS_RESPONSE = 'CLEAR_EDIT_SUBSCRIPTION_SETTINGS_RESPONSE';

export { EDIT_SUBSCRIPTION_SETTINGS, CLEAR_EDIT_SUBSCRIPTION_SETTINGS_RESPONSE };
