const GET_NOTIFICATION_CONTACTS = 'GET_NOTIFICATION_CONTACTS';
const ADD_NOTIFICATION_CONTACT = 'ADD_NOTIFICATION_CONTACT';
const DELETE_NOTIFICATION_CONTACT = 'DELETE_NOTIFICATION_CONTACT';
const NOTIFICATION_CONTACTS = 'NOTIFICATION_CONTACTS';
const GET_SUPPORT_CASES = 'GET_SUPPORT_CASES';

export {
  GET_NOTIFICATION_CONTACTS,
  ADD_NOTIFICATION_CONTACT,
  DELETE_NOTIFICATION_CONTACT,
  NOTIFICATION_CONTACTS,
  GET_SUPPORT_CASES,
};
