const USER_INFO_RESPONSE = 'USER_INFO_RESPONSE';
const GET_ORGANIZATION = 'GET_ORGANIZATION';
const GET_ORG_QUOTA = 'GET_ORG_QUOTA';

const userConstants = {
  USER_INFO_RESPONSE,
  GET_ORGANIZATION,
  GET_ORG_QUOTA,
};

export { USER_INFO_RESPONSE, GET_ORGANIZATION, GET_ORG_QUOTA };
export default userConstants;
