const USER_INFO_RESPONSE = 'USER_INFO_RESPONSE';
const GET_ORGANIZATION = 'GET_ORGANIZATION';
const SELF_TERMS_REVIEW = 'SELF_TERMS_REVIEW';

const userConstants = {
  USER_INFO_RESPONSE,
  GET_ORGANIZATION,
  SELF_TERMS_REVIEW,
};

export { USER_INFO_RESPONSE, GET_ORGANIZATION, SELF_TERMS_REVIEW };
export default userConstants;
