const VIEW_FIRST_PAGE = 'VIEW_FIRST_PAGE';
const VIEW_LAST_PAGE = 'VIEW_LAST_PAGE';
const VIEW_PREVIOUS_PAGE = 'VIEW_PREVIOUS_PAGE';
const VIEW_NEXT_PAGE = 'VIEW_NEXT_PAGE';
const VIEW_PAGE_NUMBER = 'VIEW_PAGE_NUMBER';
const SET_PER_PAGE = 'SET_PER_PAGE';
const VIEW_SET_LIST_FILTER = 'VIEW_SET_LIST_FILTER';
const VIEW_SET_LIST_FLAGS = 'VIEW_SET_LIST_FLAGS';
const VIEW_CLEAR_FILTERS_AND_FLAGS = 'VIEW_CLEAR_FILTERS_AND_FLAGS';
const VIEW_RESET_FILTERS_AND_FLAGS = 'VIEW_RESET_FILTERS_AND_FLAGS';
const VIEW_CHANGE_SORT = 'VIEW_CHANGE_SORT';
const SET_TOTAL_ITEMS = 'SET_TOTAL_ITEMS';

export {
  VIEW_FIRST_PAGE,
  VIEW_LAST_PAGE,
  VIEW_PREVIOUS_PAGE,
  VIEW_NEXT_PAGE,
  VIEW_PAGE_NUMBER,
  SET_PER_PAGE,
  VIEW_SET_LIST_FILTER,
  VIEW_SET_LIST_FLAGS,
  VIEW_CLEAR_FILTERS_AND_FLAGS,
  VIEW_RESET_FILTERS_AND_FLAGS,
  VIEW_CHANGE_SORT,
  SET_TOTAL_ITEMS,
};
