const ACCESS_REQUESTS_VIEW = 'ACCESS_REQUESTS_VIEW';
const CLUSTERS_VIEW = 'CLUSTERS_VIEW';
const ARCHIVED_CLUSTERS_VIEW = 'ARCHIVED_CLUSTERS_VIEW';
const CLUSTER_LOGS_VIEW = 'CLUSTER_LOGS_VIEW';
const OVERVIEW_VIEW = 'OVERVIEW_VIEW';
const OVERVIEW_EXPIRED_TRIALS = 'OVERVIEW_EXPIRED_TRIALS';
const CLUSTER_TRANSFER_VIEW = 'CLUSTER_TRANSFER_VIEW';

const viewConstants = {
  ACCESS_REQUESTS_VIEW,
  CLUSTERS_VIEW,
  ARCHIVED_CLUSTERS_VIEW,
  CLUSTER_LOGS_VIEW,
  OVERVIEW_VIEW,
  OVERVIEW_EXPIRED_TRIALS,
  CLUSTER_TRANSFER_VIEW,
};

export {
  ACCESS_REQUESTS_VIEW,
  CLUSTERS_VIEW,
  ARCHIVED_CLUSTERS_VIEW,
  CLUSTER_LOGS_VIEW,
  OVERVIEW_VIEW,
  OVERVIEW_EXPIRED_TRIALS,
  CLUSTER_TRANSFER_VIEW,
};
export default viewConstants;
