const CLUSTERS_VIEW = 'CLUSTERS_VIEW';
const ARCHIVED_CLUSTERS_VIEW = 'ARCHIVED_CLUSTERS_VIEW';
const CLUSTER_LOGS_VIEW = 'CLUSTER_LOGS_VIEW';
const OVERVIEW_VIEW = 'OVERVIEW_VIEW';

const viewConstants = {
  CLUSTERS_VIEW,
  ARCHIVED_CLUSTERS_VIEW,
  CLUSTER_LOGS_VIEW,
  OVERVIEW_VIEW,
};

export {
  CLUSTERS_VIEW, ARCHIVED_CLUSTERS_VIEW, CLUSTER_LOGS_VIEW, OVERVIEW_VIEW,
};
export default viewConstants;
