const GET_ROLES = 'GET_ROLES';
const GET_GRANTS = 'GET_GRANTS';

const ADD_GRANT = 'ADD_GRANT';
const DELETE_GRANT = 'DELETE_GRANT';

const CLEAR_GET_ROLES_RESPONSE = 'CLEAR_GET_ROLES_RESPONSE';
const CLEAR_GET_GRANTS_RESPONSE = 'CLEAR_GET_GRANTS_RESPONSE';
const CLEAR_ADD_GRANT_RESPONSE = 'CLEAR_ADD_GRANT_RESPONSE';

const NetworkSelfServiceConstants = {
  GET_ROLES,
  GET_GRANTS,
  ADD_GRANT,
  CLEAR_GET_ROLES_RESPONSE,
  CLEAR_GET_GRANTS_RESPONSE,
  CLEAR_ADD_GRANT_RESPONSE,
  DELETE_GRANT,
};

export {
  GET_ROLES,
  GET_GRANTS,
  ADD_GRANT,
  CLEAR_GET_ROLES_RESPONSE,
  CLEAR_GET_GRANTS_RESPONSE,
  CLEAR_ADD_GRANT_RESPONSE,
  DELETE_GRANT,
};

export default NetworkSelfServiceConstants;
