/**
 * Playwright test constants
 * Centralized location for commonly used paths and configuration values
 */

// ==================== Authentication ====================

/**
 * Path to the authentication storage state file
 * This file contains saved cookies and localStorage that preserve authentication
 * across test runs. It's generated by global-setup.ts and consumed by test fixtures.
 */
export const STORAGE_STATE_PATH = 'playwright/fixtures/storageState.json';

// ==================== Test Artifacts ====================

/**
 * Directory where HTML test reports are generated
 * Reports can be viewed by running: npx playwright show-report
 */
export const REPORTS_DIR = 'playwright-artifacts/reports';

/**
 * Directory where test artifacts (traces, videos, screenshots) are stored
 * These are generated during test failures or based on configuration
 */
export const RESULTS_DIR = 'playwright-artifacts/results';

// ==================== Configuration Files ====================

/**
 * Path to the playwright environment configuration file
 * Contains environment-specific variables like BASE_URL, credentials, etc.
 */
export const ENV_CONFIG_PATH = 'playwright.env.json';

// ==================== Test Directories ====================

/**
 * Root directory for all playwright files (matches testDir in config)
 * This is the base directory that Playwright scans for test files
 */
export const TEST_DIR = './playwright';

/**
 * Directory containing all e2e test spec files
 * This is where actual test files (*.spec.ts) are located
 */
export const E2E_DIR = 'playwright/e2e';

/**
 * Directory containing test fixtures and mock data
 */
export const FIXTURES_DIR = 'playwright/fixtures';

/**
 * Directory containing page object models
 */
export const PAGE_OBJECTS_DIR = 'playwright/page-objects';

/**
 * Directory containing test support utilities and helpers
 */
export const SUPPORT_DIR = 'playwright/support';

// ==================== Timeouts ====================

/**
 * Default timeout for test actions (15 seconds)
 * Used for actions like click, fill, etc.
 */
export const DEFAULT_ACTION_TIMEOUT = 15000;

/**
 * Default timeout for page navigation (60 seconds)
 * Used for page loads and navigation
 */
export const DEFAULT_NAVIGATION_TIMEOUT = 60000;

/**
 * Default timeout for test expectations (10 seconds)
 * Used for assertions and expect statements
 */
export const DEFAULT_EXPECT_TIMEOUT = 10000;

/**
 * Global test timeout (5 minutes)
 * Maximum time a single test can run
 */
export const GLOBAL_TEST_TIMEOUT = 300000;
