const ENTITLEMENT_OK = 'Ok';
const ENTITLEMENT_NOT_SET = 'NotSet';
const ENTITLEMENT_OVERCOMMITTED = 'Overcommitted';
const ENTITLEMENT_INCONSISTENT_SERVICES = 'InconsistentServices';
const SUBSCRIPTION_ACTIVE = 'Active';
const SUBSCRIPTION_ARCHIVED = 'Archived';
const SUBSCRIPTION_DEPROVISIONED = 'Deprovisioned';
const SUBSCRIPTION_RESERVED = 'Reserved';
const SUBSCRIPTION_STALE = 'Stale';

export {
  SUBSCRIPTION_ACTIVE,
  SUBSCRIPTION_ARCHIVED,
  SUBSCRIPTION_DEPROVISIONED,
  SUBSCRIPTION_RESERVED,
  SUBSCRIPTION_STALE,
  ENTITLEMENT_OK,
  ENTITLEMENT_NOT_SET,
  ENTITLEMENT_OVERCOMMITTED,
  ENTITLEMENT_INCONSISTENT_SERVICES,
};
